'use strict';(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[15],{1206:function(J,V,d){d.r(V);J=d(0);var h=d(68),e=d(26),m=d(683),n=d(967),v=d(966),A=d(965),w=d(28);class y{constructor(qa,Ja,xa){this.wEg=this.gpe=null;this.ta=qa;this.ia=Ja;this.yFa=xa}getId(){return"DesignerSuggestionApplicator"}applyTextToSmartArtSuggestion(qa,Ja,xa){Ja=Number.parseInvariant(Ja);qa=Object.assign(new n.a,{DAc:Object.assign(new m.a,{SuggestionSid:Ja,ShapeId:xa,CorrelationId:qa,ActiveSlideCid:this.ta.Ba.cid,
ActiveSlideSid:this.ta.Ba.sid})});this.ia.Ka(w.a.ZMa,2,qa)}previewTextToSmartArtSuggestion(qa,Ja){qa=new A.a(qa,Ja);this.yFa.W9g(qa)}dismissTextToSmartArtPreview(qa){qa=new v.a(qa);this.yFa.V9g(qa)}d1h(qa,Ja){this.gpe=qa;this.wEg=Ja}showMoreSlideSuggestions(qa){this.gpe&&(this.wEg(),this.ia.processAction(w.a.V3d,2),this.gpe(qa))}}Object(J.a)(y,"DesignerSuggestionApplicator",null,[899,873]);class u{constructor(qa){this.ia=qa}getId(){return"ActionsExecutor"}execute(qa,Ja){for(const xa of Ja)16===(xa.data?
this.ia.Ka(xa.command,2,xa.data):this.ia.processAction(xa.command,2))&&e.a.J(38412323,802,50,"Executing actions with id '{0}' failed for command '{1}'",qa,xa.command)}}Object(J.a)(u,"ExecuteActions",null,[898,873]);var E=d(25),G=d(45),I=d(35);class H{constructor(qa,Ja){this.ia=qa;this.T2c=Ja}getId(){return"FeedbackExecutor"}showFeedback(qa,Ja){if(E.AFrameworkApplication.aE)if(G.a.Va(Ja)||!this.T2c.instance){const xa={};xa.Origin=qa;this.ia.Ka(I.a.giveFeedback,2,xa)}else this.T2c.execute(xa=>{xa.hHb(Ja,
"PowerPointIdeasSurveyEnabled")})}}Object(J.a)(H,"ExecuteFeedback",null,[897,873]);var K=d(119),C=d(177),Y=d(168),M=d(13),P=d(22);class T{constructor(qa,Ja,xa,Ga,na,sa){this.eta=null;this.isFeatureEnabled=!1;this.la=xa;this.ia=qa;this.Fa=Ja;this.NG=Ga;this.Xd=na;this.yc=sa;this.S9d=!1}get qe(){return this.Xd.instance}Ocb(qa,Ja){if(this.S9d&&(this.S9d=!1,(qa=Ja.instanceId)&&qa.length&&this.Xd.instance&&(Ja=this.Xd.instance.fZ(this.eta.assetId),!Ja||!Ja.instanceId||Ja.instanceId===qa)))this.NG.hub.onIdeasPaneStateChanged(!1,
"unknown")}KL(qa,Ja,xa){if(!this.isFeatureEnabled)return 8;if(1===xa)return this.yc.Nj()?32:8;this.h4b()?this.Sjg(qa):this.xwa(qa);return 32}Ds(qa,Ja,xa){if(!this.isFeatureEnabled)return 8;if(1===xa)return 32;this.Sjg(qa);return 32}Kl(qa,Ja,xa){if(!this.isFeatureEnabled)return 8;if(1===xa)return 32;this.xwa(qa);return 32}KIe(qa,Ja,xa,Ga,na){if(!this.isFeatureEnabled)return 8;if(1===xa)return 32;qa=this.p6f();if(!qa)return 8;qa.Oga=na;this.qe.IAh(qa.instanceId);return 32}G8g(){return 32}Sjg(qa){this.h4b()&&
this.dqh(qa)}xwa(qa){this.S9d=!0;this.h4b()||this.dqh(qa);this.NG.hub.onIdeasPaneStateChanged(!0,w.a.vz(qa))}dqh(qa){qa===w.a.vLe?this.ia.Ka(w.a.aqh,2,!0):this.ia.Ka(w.a.sLe,2,!0)}p6f(){if(this.qe){const qa=this.qe.OZb(this.eta);return this.Xd.instance.fZ(qa)}return null}h4b(){const qa=this.p6f();return!!qa&&qa.taskpane.visibility}}Object(J.a)(T,"BasePaneActor",null,[]);var L=d(27),aa=d(52),Q=d(107),ea=d(40);class ia extends T{constructor(qa,Ja,xa,Ga,na,sa,Ha){super(qa,Ja,xa,Ga,sa,Ha);this.eta={};
this.eta.assetId="FA000000017";this.eta.sourceLocationOverrideResourceId=this.la.powerPointIdeasSourceLocationId;this.Xd.execute(cb=>{cb.rGd(Object(M.a)(this,this.Ocb,"onPaneClosed"))});this.isFeatureEnabled=this.la.powerPointIdeasIsEnabled;this.$u=na}ub(){this.isFeatureEnabled&&(this.ia.pa(w.a.vLe,aa.a.application,Object(M.a)(this,this.KL,"showHidePane"),4),this.ia.pa(w.a.fhd,aa.a.application,Object(M.a)(this,this.KL,"showHidePane"),4),this.ia.pa(w.a.Kbl,aa.a.application,Object(M.a)(this,this.KL,
"showHidePane"),4),this.ia.pa(w.a.Jbl,aa.a.application,Object(M.a)(this,this.KL,"showHidePane"),4),this.ia.pa(w.a.bqh,aa.a.application,Object(M.a)(this,this.KL,"showHidePane"),4),this.ia.pa(w.a.V3d,aa.a.application,Object(M.a)(this,this.Ds,"hidePane"),4),this.ia.pa(w.a.jqh,aa.a.application,Object(M.a)(this,this.Kl,"showPane"),4),this.ia.pa(w.a.BLe,aa.a.application,Object(M.a)(this,this.Kl,"showPane"),4),this.ia.pa(w.a.KIe,aa.a.application,Object(M.a)(this,this.KIe,"setPaneTitle"),4),ea.a("Designer.QueryNewPane")||
this.ia.pa(w.a.lBe,aa.a.application,Object(M.a)(this,this.G8g,"queryShowHidePane"),96),L.App.Fb.updateCommandUI())}we(){this.Fa.Bc(K.AFrame.gj).bindAction(C.KeyInputManager.Na(Y.a.ooc,1),w.a.bqh)}G8g(qa,Ja,xa,Ga,na){return Object(P.a)(Q.a,na)&&this.la.powerPointIdeasIsEnabled&&this.NG.hub?32:8}Ocb(qa,Ja){super.Ocb(qa,Ja);this.$u.Kid(JSON.stringify({IdeasPaneOpen:!1}))}xwa(qa){super.xwa(qa);this.$u.Kid(JSON.stringify({IdeasPaneOpen:!0}))}}Object(J.a)(ia,"IdeasActor",T,[]);var ja=d(1056),D=d(529),pa=
d(57),Z=d(32),oa=d(527);class Ba{constructor(qa){this.ia=qa}insertOnlinePicture(qa){qa=Object.assign(new D.a,{Action:"Insert",Caption:qa.caption,OriginalUrl:qa.sourceUrl,Height:qa.height,Width:qa.width,LicenseDisplayName:qa.licenseDisplayName,LicenseUrl:qa.licenseUrl,ThumbnailUrl:qa.thumbnailUrl,PageUrl:qa.pageUrl});this.ia.Ka(w.a.M7a,2,qa)}insertHtmlText(qa){const Ja=new ja.DictionaryPropertySet;Ja.setValue(pa.a.zT,qa.htmlText);Ja.setValue(pa.a.A9c,!1);8===this.ia.Ka(Z.a.q9c,2,Ja)&&(qa=Object.assign(new oa.a,
{okc:!1,TX:qa.htmlText}),this.ia.Ka(w.a.QGa,2,qa))}insertContentFromStreamUrl(){throw Error.notImplemented();}getId(){return"InsertContentExecutor"}}Object(J.a)(Ba,"InsertContentExecutor",null,[872,873]);class Ma{}Object(J.a)(Ma,"ConfigurationProvider",null,[]);class za{constructor(qa,Ja,xa,Ga,na,sa){e.a.J(512262857,809,50,"PPTIdeasManager - Initialize");var Ha=JSON.parse(qa.Ha("611"));for(var cb in Ha){var Za=Ha[cb];Za.runtimeJs=E.AFrameworkApplication.Fk(Ha[cb].runtimeJs,5);G.a.Va(Za.isEnabledBrs)||
(Za.isEnabled=qa.ka(Za.isEnabledBrs))}cb=qa.yba("613",0);Za=JSON.parse(qa.Ha("612"));const va=qa.Ha("664"),Fa=qa.Ec("700",0),Ca=qa.Ha("781");qa=qa.Ha("843");let La=E.AFrameworkApplication.Fk("",5);"Relative"===qa?La="":"Current"!==qa&&e.a.J(512262856,802,15,"Unknown value '{0}' for PowerPointIdeasScriptLocationOverride. Using 'Current' instead.",qa);Ha=Object.assign(new Ma,{channelId:"Ideas",registeredServices:Ha,rankingOrder:Za,rankingPromotionRate:cb,approvedOriginPattern:va,actionTrackingInterval:Fa,
surveyName:Ca,showFeedbackCard:E.AFrameworkApplication.aE,scriptLocation:La});IdeasHub.ideasHubInstance=IdeasHub.setup(Ha,sa.stb,e.a.J,[Ja,xa,Ga,na],sa.w2i());this.NMh=IdeasHub.ideasHubInstance}get hub(){return this.NMh}}Object(J.a)(za,"PPTIdeasManager",null,[870,871]);class ka{constructor(){this.pje=this.K=null}get name(){return"PowerPointWebEditor.Ideas"}Wb(qa){this.K=qa;this.K.register(y,"PowerPointWebEditor.Ideas.DesignerSuggestionApplicator").as("PowerPointWebEditor.IApplyDesignerSuggestions").ma().na(()=>
new y(qa.resolve("PowerPointWebEditor.Graph.IGraphTopologyManager"),qa.resolve("Common.IActionManagerExtended"),qa.resolve("PowerPointWebEditor.ReplaceObject.IReplaceObjectEventNotifier")));this.K.register(H,"PowerPointWebEditor.Ideas.ExecuteFeedback").as("PowerPointWebEditor.Ideas.IExecuteFeedback").ma().na(()=>new H(qa.resolve("Common.IActionManagerExtended"),qa.La("Common.ISystemInitiatedFeedback")));this.K.register(Ba,"PowerPointWebEditor.Ideas.InsertContentExecutor").as("PowerPointWebEditor.IInsertContentExecutor").ma().na(()=>
new Ba(qa.resolve("Common.IActionManagerExtended")));this.K.register(u,"PowerPointWebEditor.Ideas.ExecuteActions").as("PowerPointWebEditor.Ideas.IExecuteActions").ma().na(()=>new u(qa.resolve("Common.IActionManagerExtended")));try{e.a.J(512262855,809,50,"PPTWebEditorIdeasPackage - Resolving IInfraredRuntimeManager");const Ja=qa.resolve("PowerPointWebEditor.Infrared.IInfraredRuntimeManager");e.a.J(512262854,809,50,"PPTWebEditorIdeasPackage - Resolved IInfraredRuntimeManager");this.K.register(za,"PowerPointWebEditor.Ideas.PPTIdeasManager").as("PowerPointWebEditor.Ideas.IPPTIdeasManager").ma().na(()=>
new za(qa.resolve("Common.IAppSettingsManager"),qa.resolve("PowerPointWebEditor.IApplyDesignerSuggestions"),qa.resolve("PowerPointWebEditor.Ideas.IExecuteFeedback"),qa.resolve("PowerPointWebEditor.IInsertContentExecutor"),qa.resolve("PowerPointWebEditor.Ideas.IExecuteActions"),Ja))}catch(Ja){throw e.a.J(512262853,809,10,"PPTWebEditorIdeasPackage - {0}",Ja),Ja;}}init(){const qa=this.K.resolve("Common.IAppSettingsManager");qa.ff(()=>{const Ja=qa.ka("610"),xa=this.K.resolve("PowerPointWebEditor.IApplicationSettings").Qeb?
this.K.resolve("PowerPointWebEditor.IPPTRumTracker"):null;Ja?(this.K.resolve("PowerPointWebEditor.IInsertContentExecutor"),this.K.resolve("PowerPointWebEditor.IApplyDesignerSuggestions"),this.pje=new ia(this.K.resolve("Common.IActionManagerExtended"),this.K.resolve("Common.IFocusManager"),this.K.resolve("PowerPointWebEditor.IApplicationSettings"),this.K.resolve("PowerPointWebEditor.Ideas.IPPTIdeasManager"),this.K.resolve("PowerPointWebEditor.IInboundHelper"),this.K.La("PowerPointWebEditor.IAppForOfficeManager"),
this.K.resolve("PowerPointWebEditor.IPresentationReader")),this.pje.ub(),this.pje.we()):xa&&xa.y9(xa.F4,xa.cRd)})}dispose(){}static main(){h.a.instance.Ac(new ka)}}Object(J.a)(ka,"PPTWebEditorIdeasPackage",null,[2,3]);Type.registerNamespace("PowerPointWebEditor.Ideas");ka.main()}}]);

//# sourceMappingURL=https://res-dev.cdn.officeppe.net/1js/build/17281904/wdjs/ppteditDS.ideas.js.map