/*
 ***************************************************************************************************** !*\
    !*** D:/a/_work/1/s/ooui/.store/toposort@1.0.7-e70287510c5359da9183/node_modules/toposort/index.js ***!
    \**************************************************************************************************** no static exports found  ************************************ !*\
    !*** ./lib/DynamicScriptLoader.js ***!
    \*********************************** ./getOrderedScriptAndDependencies  ./loadScript  ./preloadScript  ********************************** !*\
    !*** ./lib/appResourceLoader.js ***!
    \********************************* ************************************************ !*\
    !*** ./lib/getOrderedScriptAndDependencies.js ***!
    \*********************************************** toposort  ********************** !*\
    !*** ./lib/index.js ***!
    \********************* ./DynamicScriptLoader  ./appResourceLoader  *************************** !*\
    !*** ./lib/loadScript.js ***!
    \************************** ****************************** !*\
    !*** ./lib/preloadScript.js ***!
    \******************************/
'use strict';var nA=window,iF=function(J){function V(w){for(var y=w[0],u=w[1],E,G,I=0,H=[];I<y.length;I++)G=y[I],Object.prototype.hasOwnProperty.call(e,G)&&e[G]&&H.push(e[G][0]),e[G]=0;for(E in u)Object.prototype.hasOwnProperty.call(u,E)&&(J[E]=u[E]);for(A&&A(w);H.length;)H.shift()()}function d(w){if(h[w])return h[w].exports;var y=h[w]={i:w,l:!1,exports:{}};J[w].call(y.exports,y,y.exports,d);y.l=!0;return y.exports}var h={},e={0:0};d.agl={1:"sha256-IJ/GoTbpqVpKtfsHlULpSaSbzw7epnrQI+UjK3e0qcQ=",2:"sha256-8YOaqmTEq7G6wzZV3LxnQDICVW+fd1+r8nu+8dlz2WQ=",
3:"sha256-zSeD56WOGLE/sk/pbm38mp4kqFxm6oDDLaUTsD/nnYQ=",4:"sha256-JurYbTKuQI0oG8Yg3VNXCsznGb8hH7D09isyPE8cR5o=",5:"sha256-WJmRQDgs60C2NsqTNRd2TzKOsiY9pQIxvA0OTCVn6V8=",6:"sha256-1PoR7UlMIbXHOOr8Elxj0qfPZIo1N70UBaPIl6OrSEQ=",7:"sha256-4F2nYzWnB7gxFb8nSPW8opaRMWwc+6tbTaSoCrYJ63Q=",8:"sha256-5zxZ5+6Za/bPOFxRVmapUGROFHSWolx0uHfmnV4L8Cg=",9:"sha256-xdfo6yioKt6GcU1em7QZGRFi+TuLqpNZVowefPUePo0=",10:"sha256-cpvTVhuSjqbbqc5quqzcYfCBIT0dFghrWR6YbXbCMSo=",11:"sha256-yiZVhBwj5mkBPspX0KjwdCcbcrLlreMHvB2CHi304ig=",
12:"sha256-M1/ZQ0HoZz1cGwgmqPaa34GnZIYSvRXCNttnfsOjEDI=",13:"sha256-E4dj2M1AwVFyfCs/vsJH/iIkINUuf7CcUiJSiOf9UqU=",14:"sha256-/0ib6RGo+ob1vkf+YlZXgv1c5/n18NM+zVQmYz9gcvc=",15:"sha256-ZvsGOzMTT9wqn464PM2zi/IVx5SqCbxxot9eTqzbuoI=",16:"sha256-xPrEJYFzl3Qwq5ud5S5LXH3Onl3GMcqr/dKjfYR8Ke4=",17:"sha256-8b6TMTMuxS6t6bsoGZ1q/XbnNLiO1e7zgJ4luN61ITU=",18:"sha256-zxMkr3XZN07f1k5ZUMO8s9B3BrbtvYV/3zo3GaiOHew="};d.e=function(w){var y=[],u=e[w];if(0!==u)if(u)y.push(u[2]);else{var E=new Promise(function(C,Y){u=e[w]=
[C,Y]});y.push(u[2]=E);var G=document.createElement("script");G.charset="utf-8";G.timeout=120;d.lek&&G.setAttribute("nonce",d.lek);G.src=d.p+"ppteditDS."+({1:"core",2:"chronos1",3:"ext",4:"presence1",5:"chronosslim",6:"extcommon",7:"comment",8:"chronos2",9:"sortergrid",10:"appforoffice",11:"augloop",12:"presence",13:"smartlookup",14:"infrared",15:"ideas",16:"capture",17:"internal",18:"animationpreview"}[w]||w)+".js";0!==G.src.indexOf(window.location.origin+"/")&&(G.crossOrigin="anonymous");var I=
Error();var H=function(C){G.onerror=G.onload=null;clearTimeout(K);var Y=e[w];if(0!==Y){if(Y){var M=C&&("load"===C.type?"missing":C.type);C=C&&C.target&&C.target.src;I.message="Loading chunk "+w+" failed.\n("+M+": "+C+")";I.name="ChunkLoadError";I.type=M;I.request=C;Y[1](I)}e[w]=void 0}};var K=setTimeout(function(){H({type:"timeout",target:G})},12E4);G.onerror=G.onload=H;G.integrity=d.agl[w];G.crossOrigin="anonymous";document.head.appendChild(G)}return Promise.all(y)};d.m=J;d.c=h;d.d=function(w,y,
u){d.o(w,y)||Object.defineProperty(w,y,{enumerable:!0,get:u})};d.r=function(w){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(w,Symbol.toStringTag,{value:"Module"});Object.defineProperty(w,"__esModule",{value:!0})};d.t=function(w,y){y&1&&(w=d(w));if(y&8||y&4&&"object"===typeof w&&w&&w.A$)return w;var u=Object.create(null);d.r(u);Object.defineProperty(u,"default",{enumerable:!0,value:w});if(y&2&&"string"!=typeof w)for(var E in w)d.d(u,E,function(G){return w[G]}.bind(null,E));
return u};d.n=function(w){var y=w&&w.A$?function(){return w["default"]}:function(){return w};d.d(y,"a",y);return y};d.o=function(w,y){return Object.prototype.hasOwnProperty.call(w,y)};d.p="";var m=window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[],n=m.push.bind(m);m.push=V;m=m.slice();for(var v=0;v<m.length;v++)V(m[v]);var A=n;return d(d.s=18)}([function(J,V,d){d.d(V,"a",function(){return h});d.d(V,"b",function(){return e});const h=(m,n,v,A)=>{m.prototype.constructor=m;m.__typeName=n;
m.__class=!0;v&&(m.__baseType=v,m.__basePrototypePending=!1);0<A.length&&(m.__interfaces=A)},e=(m,n,v=!1)=>{n.__typeName=m;n.__string=m;n.__flags=v;n.__enum=!0;n.parse=A=>n[A];n.toString=A=>n[A];n.getName=()=>m}},function(J,V,d){J=d(0);class h extends Sys.EventArgs{constructor(m){super();this.Ui=m}}Object(J.a)(h,"UnobservedTaskExceptionEventArgs",Sys.EventArgs,[]);d.d(V,"a",function(){return e});class e{aRe(m){m.Mmc()}static get events(){return e.Zxa||(e.Zxa=new Sys.EventHandlerList)}static get default(){return e._default}static get current(){return e.$x}static set current(m){e.$x=
m}static Zgh(m,n){const {Task:v}=d(2);n=n||e.current;n===e._default?window.setTimeout(e.cWk(m,n),0):v.Create(m).Start$Scheduler(n)}static fCk(m,n){const v=e.events.getHandler("UnobservedException");v&&v(m,new h(n))}static cWk(m,n){return()=>{const v=e.current;e.current=n;m();e.current=v}}}e.Zxa=null;Object(J.a)(e,"TaskScheduler",null,[])},function(J,V,d){d.r(V);J=d(0);var h=d(13),e=d(11),m=d(6),n=d(8);class v{constructor(E){this.Hm=E}Qcc(E){this.Hm.OC(E,null,0,null)}get isCompleted(){return this.Hm.isCompleted}Dba(){if(this.Hm.Wl)throw this.Hm.Ui;
if(this.Hm.Dn)throw n.a.FEc();}}Object(J.a)(v,"TaskAwaiter",null,[99]);class A{constructor(E,G,I){this.task=this.jvh=this.handler=null;this.token=E;this.options=G;this.eIb=I}}Object(J.a)(A,"Continuation",null,[]);var w=d(1);class y{constructor(){this.I0=[];this.YKa=!1;w.a.Zgh(Object(h.a)(this,this.complete,"complete"),null)}complete(){this.YKa=!0;for(const E of this.I0)E()}get isCompleted(){return this.YKa}Dba(){}Qcc(E){this.isCompleted?E():this.I0.push(E)}}Object(J.a)(y,"YieldAwaitable",null,[99]);
d.d(V,"Task",function(){return u});class u{constructor(){this.Sn=this.J_a=this.ppd=this.fmb=this.iKb=this.eib=this.Rpc=null;this.VF=1}get id(){this._id||(this._id=++u.LQh);return this._id}get status(){return this.VF}get Ui(){return this.J_a}Pfb(E){n.a.trg(E)?this.Z_():(this.J_a=E,this.tC(!1))}get Dn(){return 4===this.status}get isCompleted(){return 3<this.status}get Wl(){return 5===this.status}g(){return new v(this)}Z_(){this.t0(!1)||u.dwh()}t0(E){if(this.isCompleted||!E&&3===this.status)return!1;
this.VF=4;this.Tgh();return!0}tC(E){this.Pql(E)||u.dwh()}Pql(E){if(this.isCompleted)return!1;this.VF=E?6:5;this.Tgh();return!0}Tgh(){const E=this.Rpc;this.Rpc=null;let G=!1;if(E)for(const I of E)G=this.jxh(I)||G;this.Ui&&!G&&w.a.fCk(this,this.Ui)}jxh(E){if(E.token&&E.token.PCa)return E.task&&E.task.t0(!1),!1;const G=this.rli(E);E.task?u.zti(E,G,E.eIb):u.xti(E,G,E.eIb,E.handler||(()=>{E.jvh(this)}));return G}rli(E){return this.Wl&&E.options&2||this.Dn&&E.options&1||6===this.status&&E.options&4?!1:
!0}TU(E,G,I,H){E=Object.assign(new A(G,I,H),{task:E});this.pFd(E)}OC(E,G,I,H){E=Object.assign(new A(G,I,H),{handler:E,token:G,eIb:H});this.pFd(E)}OCT(E,G,I,H){E=Object.assign(new A(G,I,H),{jvh:E,token:G,eIb:H});this.pFd(E)}pFd(E){E.eIb=E.eIb||w.a.current;if(E.token&&E.task){if(E.token.PCa&&this.Kgg(E))return;E.token.R(()=>{this.Kgg(E)})}this.isCompleted?this.jxh(E):this.Rpc=e.a(this.Rpc,E)}Kgg(E){return E.task?E.task.t0(!1):!1}CW(E){return this.continueWith(E)}CWC(E,G){E=d(5).ContinuableTask.C(E,
this);this.TU(E,G,0,null);return E}CWo(E,G){return this.continueWith(E,G)}continueWith(E,G=0,I=null,H=null){E=d(5).ContinuableTask.C(E,this);this.TU(E,I,G,H);return E}CWT(E,G){E=d(5).ContinuableTask.C(E,this);this.TU(E,null,0,G);return E}CWO(E,G){E=d(5).ContinuableTask.CO(E,G,this);this.TU(E,null,0,null);return E}CWOC(E,G,I){E=d(5).ContinuableTask.CO(E,G,this);this.TU(E,I,0,null);return E}CWOo(E,G,I){E=d(5).ContinuableTask.CO(E,G,this);this.TU(E,null,I,null);return E}CWOT(E,G,I){E=d(5).ContinuableTask.CO(E,
G,this);this.TU(E,null,0,I);return E}CWCT(E,G,I,H){E=d(5).ContinuableTask.C(E,this);this.TU(E,G,I,H);return E}CWOCT(E,G,I,H,K){E=d(5).ContinuableTask.CO(E,G,this);this.TU(E,I,H,K);return E}CWR(E){return this.Cti(E)}Cti(E){E=d(7).ContinuableTask$1.C(E,this);this.TU(E,null,0,null);return E}CWRCC(E,G){E=d(7).ContinuableTask$1.C(E,this);this.TU(E,G,0,null);return E}CWRCo(E,G){E=d(7).ContinuableTask$1.C(E,this);this.TU(E,null,G,null);return E}CWRT(E,G){E=d(7).ContinuableTask$1.C(E,this);this.TU(E,null,
0,G);return E}CWRO(E,G){E=d(7).ContinuableTask$1.CO(E,G,this);this.TU(E,null,0,null);return E}CWRCT(E,G,I,H){E=d(7).ContinuableTask$1.C(E,this);this.TU(E,G,I,H);return E}CWROCT(E,G,I,H,K){E=d(7).ContinuableTask$1.CO(E,G,this);this.TU(E,I,H,K);return E}start(){this.Start$Scheduler(w.a.current)}Start$Scheduler(E){if(1!==this.status)throw Error.invalidOperation();this.fmb=E;this.VF=2;E.JBe(this)}Mmc(){if(this.ppd&&this.ppd.PCa)this.isCompleted||this.Z_();else if(!this.isCompleted){var E=w.a.current;
this.fmb=this.fmb||w.a.current;w.a.current=this.fmb||w.a.current;this.bed();w.a.current=E}}bed(){this.VF=3;try{if(!this.execute())throw Error.invalidOperation();this.tC(!0)}catch(E){n.a.trg(E)?this.t0(!0):this.Pfb(E)}}execute(){if(this.eib)this.eib();else if(this.iKb)this.iKb(this.Sn);else return!1;return!0}static get factory(){return u.CKa}static Create(E){return Object.assign(new u,{eib:E})}static Create$object(E,G){return Object.assign(new u,{iKb:E,Sn:G})}static dwh(){throw Error.invalidOperation();
}static xti(E,G,I,H){G&&(E.options&8?H():w.a.Zgh(H,I))}static zti(E,G,I){const H=E.task;G?E.options&8?H.Mmc():1===H.status&&(H.ppd=E.token,H.Start$Scheduler(I||w.a.current)):H.Z_()}static delay(E){const G=new (d(16).CompletableTask);window.setTimeout(Object(h.a)(G,G.Bg,"setResult"),E);return G}static y(){return new y}static wt(E){const G=new (d(12).CompletableTask$1);G.Bg(E);return G}static WAA(...E){return u.AAl.apply(null,E)}static AAl(...E){return u.WhenAllEnumerable(m.asEnumerable(E))}static WAE(E){return u.WhenAllEnumerable(E)}static WhenAllEnumerable(E){let G=
null,I=!1,H=0;const K=new (d(16).CompletableTask),C=Y=>{Y.Wl&&(G=e.a(G,Y.Ui));Y.Dn&&(I=!0);H--;H||(G?K.SEsA(G):I?K.Z_():K.Bg())};H++;for(const Y of E)H++,Y.isCompleted?C(Y):Y.OCT(C,null,0,null);H--;H||(G?K.SEsA(G):I?K.Z_():K.Bg());return K}static When(E){let G=new (d(12).CompletableTask$1);const I=H=>{G&&(G.Bg(H),G=null)};for(const H of E){if(H.isCompleted)return u.wt(H);H.OCT(I,null,0,null)}return G}static When$Result(E){let G=new (d(12).CompletableTask$1);for(const I of E){if(I.isCompleted)return u.wt(I);
I.OCT(H=>{G&&(G.Bg(H),G=null)},null,0,null)}return G}}u.LQh=0;Object(J.a)(u,"Task",null,[])},,function(J,V,d){J=d(0);var h=d(2),e=d(8);class m{constructor(v){this.Hm=v}Qcc(v){this.Hm.OC(v,null,0,null)}get isCompleted(){return this.Hm.isCompleted}Dba(){if(this.Hm.Wl)throw this.Hm.Ui;if(this.Hm.Dn)throw e.a.FEc();return this.Hm.result}}Object(J.a)(m,"TaskAwaiter$1",null,[99]);d.d(V,"a",function(){return n});class n extends h.Task{constructor(){super();this.qsd=this.psd=null}execute(){if(this.psd)this.Qjc(this.psd());
else if(this.qsd)this.Qjc(this.qsd(this.Sn));else return!1;return!0}get result(){if(6!==this.status)throw Error.invalidOperation();return this.qx}Qjc(v){this.qx=v}G(){return new m(this)}static C(v){const A=new n;A.psd=v;return A}static CO(v,A){const w=new n;w.qsd=v;w.Sn=A;return w}}Object(J.a)(n,"Task$1",h.Task,[])},function(J,V,d){d.r(V);d.d(V,"ContinuableTask",function(){return h});J=d(0);d=d(2);class h extends d.Task{constructor(){super();this._parent=this.qVe=this.wnd=null}execute(){this.wnd?
this.wnd(this._parent):this.qVe(this._parent,this.Sn);return!0}static C(e,m){const n=new h;n.wnd=e;n._parent=m;return n}static CO(e,m,n){const v=new h;v.qVe=e;v.Sn=m;v._parent=n;return v}}Object(J.a)(h,"ContinuableTask",d.Task,[])},function(J,V,d){d.r(V);J=d(0);var h=d(10);class e{constructor(gc){this.$$ge=this.getEnumerator;this.mH=gc}getEnumerator(){return new h.a(this.mH)}[Symbol.iterator](){return this.mH[Symbol.iterator]()}}Object(J.a)(e,"ArrayEnumerable$1",null,[143]);var m=d(17),n=d(21);class v{constructor(gc){this.aj=
null;this.Eu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=gc}getEnumerator(){return this.Eu?new v(this.kt):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.aj.get_current()}moveNext(){this.aj||(this.aj=this.kt.getEnumerator());return this.aj.moveNext()}reset(){this.aj=null}}Object(J.a)(v,"CastEnumerable",null,[143,145]);class A{constructor(gc,rb){this.asd=!1;this.I_a=null;this.Eu=
!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.O$=gc;this.FQb=rb}getEnumerator(){return this.Eu?new A(this.O$,this.FQb):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.I_a.$$cu()}moveNext(){this.I_a||(this.I_a=this.O$.$$ge());if(this.I_a.$$mn())return!0;if(this.asd)return!1;this.asd=!0;this.I_a=this.FQb.$$ge();return this.I_a.$$mn()}reset(){this.asd=!1;this.I_a=null}}Object(J.a)(A,
"ConcatEnumerable",null,[143,145]);class w{constructor(){this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset}getEnumerator(){return this}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){throw Error.invalidOperation();}moveNext(){return!1}reset(){}}Object(J.a)(w,"EmptyEnumerator",null,[143,145]);class y{constructor(gc){this.wb=null;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.Irc=gc}get_current(){return this.$x}moveNext(){this.wb||
(this.wb=this.Irc());const gc=this.wb.next();this.$x=gc.value;return!gc.done}reset(){this.wb=null}}Object(J.a)(y,"IteratorEnumerator",null,[145]);class u{constructor(gc){this.$$ge=this.getEnumerator;this.Irc=gc}getEnumerator(){return new y(this.Irc)}[Symbol.iterator](){return this.Irc()}}Object(J.a)(u,"IteratorEnumerable",null,[143]);class E{constructor(gc,rb,Ua,pb,Ub){this.$$ge=this.getEnumerator;this.kt=gc;this.wYe=rb;this._parent=pb;this.XIh=Ua?(Bc,Gc)=>Ua.compare(Bc,Gc):E.Gpi.bind(E);this.wQh=
Ub?-1:1}getEnumerator(){const gc=d(6).toArray(this.kt);gc.sort((rb,Ua)=>this.rXf(rb,Ua));return new h.a(gc)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}rXf(gc,rb){if(this._parent){const Ua=this._parent.rXf(gc,rb);if(Ua)return Ua}return this.XIh(this.wYe(gc),this.wYe(rb))*this.wQh}static Gpi(gc,rb){return gc<rb?-1:gc>rb?1:0}}Object(J.a)(E,"OrderByEnumerable",null,[1719,143]);class G{constructor(gc,rb){this.Lh=0;this.Eu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=
this.moveNext;this.$$rst=this.reset;this._element=gc;this.Gk=rb}getEnumerator(){return this.Eu?(new G(this._element,this.Gk)).getEnumerator():(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this._element}moveNext(){if(this.Lh>=this.Gk)return!1;this.Lh++;return!0}reset(){this.Lh=0}}Object(J.a)(G,"RepeatEnumerator",null,[143,145]);class I{constructor(gc,rb,Ua){this.Eu=!1;this.Lh=0;this.aj=null;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;
this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=gc;this.k0a=Ua;this.ZQb=rb}getEnumerator(){return this.Eu?new I(this.kt,this.ZQb,this.k0a):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.$x}moveNext(){this.aj||(this.aj=this.kt.$$ge());return this.aj.$$mn()?(this.$x=this.$dd(this.aj.$$cu()),this.Lh++,!0):!1}next(){this.aj||(this.aj=this.kt.$$ge());return this.aj.$$mn()?(this.$x=this.$dd(this.aj.$$cu()),this.Lh++,{done:!1,value:this.$x}):
{done:!0,value:void 0}}reset(){this.aj=null;this.Lh=-1}$dd(gc){return this.k0a?this.k0a(gc,this.Lh):this.ZQb(gc)}}Object(J.a)(I,"SelectEnumerator",null,[143,145]);class H{constructor(gc,rb,Ua){this.Eu=!1;this.Lh=0;this.aj=this.v1a=null;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=gc;this.ZQb=rb;this.k0a=Ua}getEnumerator(){return this.Eu?new H(this.kt,this.ZQb,this.k0a):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.v1a.$$cu()}moveNext(){if(this.v1a&&
this.v1a.$$mn())return!0;do{this.v1a=null;this.aj||(this.aj=this.kt.$$ge());if(!this.aj.$$mn())return!1;this.v1a=this.$dd(this.aj.$$cu()).$$ge();this.Lh++}while(!this.v1a.$$mn());return!0}reset(){this.v1a=this.aj=null;this.Lh=0}$dd(gc){return this.k0a?this.k0a(gc,this.Lh):this.ZQb(gc)}}Object(J.a)(H,"SelectManyEnumerator",null,[143,145]);class K{constructor(gc,rb){this.aj=null;this.Eu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=
gc;this.Gk=rb}getEnumerator(){return this.Eu?new K(this.kt,this.Gk):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.aj.$$cu()}moveNext(){if(!this.aj){this.aj=this.kt.$$ge();for(let gc=0;gc<this.Gk;gc++)if(!this.aj.$$mn())return!1}return this.aj.$$mn()}reset(){this.aj=null}}Object(J.a)(K,"SkipEnumerator",null,[143,145]);class C{constructor(gc,rb,Ua){this.Eu=!1;this.Lh=0;this.aj=null;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=
this.moveNext;this.$$rst=this.reset;this.kt=gc;this.YQb=rb;this.j0a=Ua}getEnumerator(){return this.Eu?new C(this.kt,this.YQb,this.j0a):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.aj.$$cu()}moveNext(){if(this.aj)return this.aj.$$mn();for(this.aj=this.kt.$$ge();this.aj.$$mn();){if(!this.FTd(this.aj.$$cu()))return!0;this.Lh++}return!1}reset(){this.aj=null;this.Lh=0}FTd(gc){return this.j0a?this.j0a(gc,this.Lh):this.YQb(gc)}}Object(J.a)(C,"SkipWhileEnumerator",
null,[143,145]);class Y{constructor(gc,rb){this.Lh=0;this.aj=null;this.Eu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=gc;this.Gk=rb}getEnumerator(){return this.Eu?new Y(this.kt,this.Gk):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.aj.$$cu()}moveNext(){this.aj||(this.aj=this.kt.$$ge());if(this.Lh>=this.Gk)return!1;this.Lh++;return this.aj.$$mn()}reset(){this.aj=null}}Object(J.a)(Y,
"TakeEnumerator",null,[143,145]);class M{constructor(gc,rb,Ua){this.Eu=!1;this.Lh=0;this.aj=null;this.Qpd=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=gc;this.YQb=rb;this.j0a=Ua}getEnumerator(){return this.Eu?new M(this.kt,this.YQb,this.j0a):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.aj.$$cu()}moveNext(){if(this.Qpd)return!1;this.aj||(this.aj=this.kt.$$ge());if(!this.aj.$$mn()||
!this.FTd(this.aj.$$cu()))return this.Qpd=!0,this.aj=null,!1;this.Lh++;return!0}reset(){this.aj=null;this.Lh=0}FTd(gc){return this.j0a?this.j0a(gc,this.Lh):this.YQb(gc)}}Object(J.a)(M,"TakeWhileEnumerator",null,[143,145]);class P{constructor(gc,rb){this.aj=null;this.Eu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.kt=gc;this.gmb=rb}getEnumerator(){return this.Eu?new P(this.kt,this.gmb):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.aj.$$cu()}moveNext(){this.aj||
(this.aj=this.kt.$$ge());for(;this.aj.$$mn();)if(this.gmb(this.aj.$$cu()))return!0;return!1}next(){this.aj||(this.aj=this.kt.$$ge());for(;this.aj.$$mn();)if(this.gmb(this.aj.$$cu()))return{done:!1,value:this.aj.$$cu()};return{done:!0,value:void 0}}reset(){this.aj=null}}Object(J.a)(P,"WhereEnumerator",null,[143,145]);class T{constructor(gc,rb,Ua){this.wwc=this.yMb=null;this.Eu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.O$=gc;this.FQb=
rb;this.Yrf=Ua}getEnumerator(){return this.Eu?new T(this.O$,this.FQb,this.Yrf):(this.Eu=!0,this)}[Symbol.iterator](){return Object(n.a)(this.getEnumerator())}get_current(){return this.$x}moveNext(){this.yMb||(this.yMb=this.O$.$$ge(),this.wwc=this.FQb.$$ge());return this.yMb.$$mn()&&this.wwc.$$mn()?(this.$x=this.Yrf(this.yMb.$$cu(),this.wwc.$$cu()),!0):!1}reset(){this.wwc=this.yMb=null}}Object(J.a)(T,"ZipEnmerator",null,[143,145]);d.d(V,"asEnumerable",function(){return L});d.d(V,"fromIterator",function(){return aa});
d.d(V,"select",function(){return Q});d.d(V,"Si",function(){return ea});d.d(V,"SMi",function(){return ia});d.d(V,"selectMany",function(){return ja});d.d(V,"skip",function(){return D});d.d(V,"skipWhile",function(){return pa});d.d(V,"SWI",function(){return Z});d.d(V,"take",function(){return oa});d.d(V,"takeWhile",function(){return Ba});d.d(V,"TW",function(){return Ma});d.d(V,"where",function(){return za});d.d(V,"first",function(){return ka});d.d(V,"FT",function(){return qa});d.d(V,"firstOrDefault",function(){return Ja});
d.d(V,"FDT",function(){return xa});d.d(V,"last",function(){return Ga});d.d(V,"LT",function(){return na});d.d(V,"lastOrDefault",function(){return sa});d.d(V,"LDT",function(){return Ha});d.d(V,"cast",function(){return cb});d.d(V,"any",function(){return Za});d.d(V,"AT",function(){return va});d.d(V,"all",function(){return Fa});d.d(V,"count",function(){return Ca});d.d(V,"Ct",function(){return La});d.d(V,"CT",function(){return nb});d.d(V,"aggregate",function(){return Nb});d.d(V,"AgS",function(){return Rb});
d.d(V,"AgSS",function(){return Ya});d.d(V,"concat",function(){return Qb});d.d(V,"repeat",function(){return bb});d.d(V,"zip",function(){return Bb});d.d(V,"orderBy",function(){return Eb});d.d(V,"OBc",function(){return tb});d.d(V,"orderByDescending",function(){return Yb});d.d(V,"OBdc",function(){return Tc});d.d(V,"thenBy",function(){return ib});d.d(V,"TBc",function(){return Zb});d.d(V,"thenByDescending",function(){return Cc});d.d(V,"TBDc",function(){return ob});d.d(V,"toList",function(){return cc});
d.d(V,"toArray",function(){return sb});d.d(V,"toDictionary",function(){return mb});d.d(V,"TD",function(){return Pb});d.d(V,"SumS",function(){return dc});d.d(V,"MinS",function(){return mc});d.d(V,"MaxS",function(){return Mb});d.d(V,"empty",function(){return Kc});const L=gc=>new e(gc),aa=gc=>new u(gc),Q=(gc,rb)=>new I(gc,rb,null),ea=(gc,rb)=>new I(gc,null,rb),ia=(gc,rb)=>new H(gc,null,rb),ja=(gc,rb)=>new H(gc,rb,null),D=(gc,rb)=>new K(gc,rb),pa=(gc,rb)=>new C(gc,rb,null),Z=(gc,rb)=>new C(gc,null,rb),
oa=(gc,rb)=>new Y(gc,rb),Ba=(gc,rb)=>new M(gc,rb,null),Ma=(gc,rb)=>new M(gc,null,rb),za=(gc,rb)=>new P(gc,rb),ka=gc=>{gc=gc.$$ge();if(!gc.$$mn())throw Error.argumentNull("source");return gc.$$cu()},qa=(gc,rb)=>{gc=gc.$$ge();do if(!gc.$$mn())throw Error.argumentNull("source");while(!rb(gc.$$cu()));return gc.$$cu()},Ja=(gc,rb=null)=>{gc=gc.$$ge();return gc.$$mn()?gc.$$cu():rb},xa=(gc,rb,Ua=null)=>{gc=gc.$$ge();do if(!gc.$$mn())return Ua;while(!rb(gc.$$cu()));return gc.$$cu()},Ga=gc=>{gc=gc.$$ge();if(!gc.$$mn())throw Error.argumentNull("source");
let rb;do rb=gc.$$cu();while(gc.$$mn());return rb},na=(gc,rb)=>{gc=gc.$$ge();for(var Ua;(Ua=gc.$$mn())&&!rb(gc.$$cu()););if(!Ua)throw Error.argumentNull("source");for(Ua=gc.$$cu();gc.$$mn();)rb(gc.$$cu())&&(Ua=gc.$$cu());return Ua},sa=(gc,rb=null)=>{gc=gc.$$ge();if(!gc.$$mn())return rb;do rb=gc.$$cu();while(gc.$$mn());return rb},Ha=(gc,rb,Ua=null)=>{gc=gc.$$ge();let pb;for(;(pb=gc.$$mn())&&!rb(gc.$$cu()););if(!pb)return Ua;for(Ua=gc.$$cu();gc.$$mn();)rb(gc.$$cu())&&(Ua=gc.$$cu());return Ua},cb=gc=>
new v(gc),Za=gc=>gc.$$ge().$$mn(),va=(gc,rb)=>{for(const Ua of gc)if(rb(Ua))return!0;return!1},Fa=(gc,rb)=>{for(const Ua of gc)if(!rb(Ua))return!1;return!0},Ca=gc=>{let rb=0;for(const Ua of gc)rb++;return rb},La=gc=>{let rb=0;for(const Ua of gc)rb++;return rb},nb=(gc,rb)=>{gc=gc.$$ge();let Ua=0;for(;gc.$$mn();)rb(gc.$$cu())&&Ua++;return Ua},Nb=(gc,rb)=>{gc=gc.$$ge();if(!gc.$$mn())throw Error.invalidOperation("source contains no elements");let Ua=gc.$$cu();for(;gc.$$mn();)Ua=rb(Ua,gc.$$cu());return Ua},
Rb=(gc,rb,Ua)=>{for(const pb of gc)rb=Ua(rb,pb);return rb},Ya=(gc,rb,Ua,pb)=>{for(const Ub of gc)rb=Ua(rb,Ub);return pb(rb)},Qb=(gc,rb)=>new A(gc,rb),bb=(gc,rb)=>new G(gc,rb),Bb=(gc,rb,Ua)=>new T(gc,rb,Ua),Eb=(gc,rb)=>new E(gc,rb,null,null,!1),tb=(gc,rb,Ua)=>new E(gc,rb,Ua,null,!1),Yb=(gc,rb)=>new E(gc,rb,null,null,!0),Tc=(gc,rb,Ua)=>new E(gc,rb,Ua,null,!0),ib=(gc,rb)=>new E(gc,rb,null,gc,!1),Zb=(gc,rb,Ua)=>new E(gc,rb,Ua,gc,!1),Cc=(gc,rb)=>new E(gc,rb,null,gc,!0),ob=(gc,rb,Ua)=>new E(gc,rb,Ua,gc,
!0),cc=gc=>{const rb=new m.a;for(const Ua of gc)rb.add(Ua);return rb},sb=gc=>cc(gc).toArray(),mb=(gc,rb)=>{const Ua=new (d(14).ScriptSharpLegacyMap);for(const pb of gc)Ua.add(rb(pb),pb);return Ua},Pb=(gc,rb,Ua)=>{const pb=new (d(14).ScriptSharpLegacyMap);for(const Ub of gc)pb.add(rb(Ub),Ua(Ub));return pb},dc=(gc,rb)=>{let Ua=0;for(const pb of gc)Ua+=rb(pb);return Ua},mc=(gc,rb)=>{let Ua=Number.POSITIVE_INFINITY;for(const pb of gc)gc=rb(pb),gc<Ua&&(Ua=gc);return Ua},Mb=(gc,rb)=>{let Ua=Number.NEGATIVE_INFINITY;
for(const pb of gc)gc=rb(pb),gc>Ua&&(Ua=gc);return Ua},Kc=()=>new w},function(J,V,d){d.r(V);d.d(V,"ContinuableTask$1",function(){return h});J=d(0);d=d(4);class h extends d.a{constructor(){super();this._parent=this.rVe=this.xnd=null}execute(){this.xnd?this.Qjc(this.xnd(this._parent)):this.Qjc(this.rVe(this._parent,this.Sn));return!0}static C(e,m){const n=new h;n.xnd=e;n._parent=m;return n}static CO(e,m,n){const v=new h;v.rVe=e;v.Sn=m;v._parent=n;return v}}Object(J.a)(h,"ContinuableTask$1",d.a,[])},
function(J,V,d){J=d(0);var h=d(11);class e{constructor(n,v,A){this.BJ=!1;this.eib=n;this.iKb=v;this.Sn=A}get disposed(){return this.BJ}Mmc(){this.disposed||(this.eib?this.eib():this.iKb(this.Sn))}dispose(){this.BJ=!0}}Object(J.a)(e,"CancellationTokenRegistration",null,[106]);d.d(V,"a",function(){return m});class m{constructor(n){this.gQb=null;this.x6e=!1;this.mIh=n}get PCa(){return this.x6e}get rii(){return this.mIh}R(n){return this.register(n)}register(n){n=new e(n,null,null);this.Yah(n);return n}RO(n,
v){n=new e(null,n,v);this.Yah(n);return n}Yah(n){this.PCa?n.Mmc():this.gQb=h.a(this.gQb,n)}cancel(n){if(!this.rii)throw Error.invalidOperation("CanBeCanceled is false");if(!this.PCa&&(this.x6e=!0,n&&this.gQb))for(const v of this.gQb)v.Mmc()}static FEc(){return Error.create("OperationCanceledException: Task canceled",{["$$canceled"]:!0})}static get none(){return m.QQh}static trg(n){return n[m.OMi]}}m.OMi="$$canceled";m.QQh=new m(!1);Object(J.a)(m,"CancellationToken",null,[])},function(J,V,d){d.d(V,
"a",function(){return h});d.d(V,"b",function(){return e});const h=m=>{const n=[];for(const v of m)n.push(v);return Error.create("AggregateException: Aggregate exceptions",{["Exceptions"]:n})},e=m=>{const n=[];for(const v of m)n.push(v);return Error.create("AggregateException: Aggregate exceptions",{["Exceptions"]:n})}},function(J,V,d){d.d(V,"a",function(){return h});J=d(0);class h{constructor(e){this.Lh=-1;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.mH=e}get_current(){if(-1===
this.Lh||this.Lh>=this.mH.length)throw Error.invalidOperation();return this.mH[this.Lh]}moveNext(){this.Lh++;return this.Lh<this.mH.length}reset(){this.Lh=-1}next(){this.Lh++;return this.Lh<this.mH.length?{done:!1,value:this.mH[this.Lh]}:{done:!0,value:void 0}}}Object(J.a)(h,"ArrayEnumerator$1",null,[145])},function(J,V,d){d.d(V,"a",function(){return h});const h=(e,m)=>e?(e.push(m),e):[m]},function(J,V,d){d.r(V);d.d(V,"CompletableTask$1",function(){return e});J=d(0);V=d(4);var h=d(9);class e extends V.a{constructor(){super()}SEsE(m){this.Pfb(h.a(m))}SEsA(m){this.Pfb(h.b(m))}SE(m){this.Pfb(m)}Bg(m){this.Qjc(m);
this.tC(!0)}}Object(J.a)(e,"CompletableTask$1",V.a,[])},function(J,V,d){d.d(V,"a",function(){return h});const h=(e,m,n)=>{n=`$$d_${n}`;null==e[n]&&(e[n]=m.bind(e));return e[n]}},function(J,V,d){d.r(V);d.d(V,"ScriptSharpLegacyMap",function(){return v});J=d(0);var h=d(13),e=d(21),m=d(15),n=d(6);class v{constructor(){this.ep=new Map;this.getEnumerator=this.pYd}$$ge(){return n.select(n.fromIterator(Object(h.a)(this.ep,this.ep.entries,"entries")),A=>new m.a(A[0],A[1])).$$ge()}pYd(){return this.$$ge()}get count(){return this.ep.size}get keys(){return n.fromIterator(Object(h.a)(this.ep,
this.ep.keys,"keys"))}get values(){return n.fromIterator(Object(h.a)(this.ep,this.ep.values,"values"))}Akvp(A){if(this.ep.has(A.key))throw Error.create("DuplicateKeyException");this.ep.set(A.key,A.value)}ga(A){const {value:w,returnValue:y}=this.Of(A,null);if(!y)throw Error.create("KeyNotFoundException");return w}$(A,w){this.ep.set(A,w);return w}add(A,w){if(this.ep.has(A))throw Error.create("DuplicateKeyException");this.ep.set(A,w)}Jb(A){return this.ep.has(A)}remove(A){return this.ep.delete(A)}Of(A,
w=null){return this.ep.has(A)?{returnValue:!0,value:this.ep.get(A)}:{returnValue:!1,value:w}}[Symbol.iterator](){return Object(e.a)(this.getEnumerator())}}Object(J.a)(v,"ScriptSharpLegacyMap",null,[144,143,1])},function(J,V,d){d.d(V,"a",function(){return h});J=d(0);class h{constructor(e,m){this.value=m;this.key=e}}Object(J.a)(h,"KeyValuePair",null,[])},function(J,V,d){d.r(V);d.d(V,"CompletableTask",function(){return e});J=d(0);V=d(2);var h=d(9);class e extends V.Task{constructor(){super()}SEsE(m){this.Pfb(h.a(m))}SEsA(m){this.Pfb(h.b(m))}SE(m){this.Pfb(m)}Bg(){this.tC(!0)}}
Object(J.a)(e,"CompletableTask",V.Task,[])},function(J,V,d){J=d(0);var h=d(10);class e{constructor(n){this.Lh=-1;this.mH=n}get_current(){if(-1===this.Lh||this.Lh>=this.mH.length)throw Error.invalidOperation();return this.mH[this.Lh]}moveNext(){this.Lh++;return this.Lh<this.mH.length}reset(){this.Lh=-1}next(){this.Lh++;return this.Lh<this.mH.length?{done:!1,value:this.mH[this.Lh]}:{done:!0,value:void 0}}}Object(J.a)(e,"ArrayEnumerator",null,[0]);d.d(V,"a",function(){return m});class m{constructor(n=
null){this.$$ge=this.$$lge;this.getEnumerator=this.pYd;this.kB=n?n:[]}$$lge(){return new h.a(this.kB)}pYd(){return new e(this.kB)}[Symbol.iterator](){return this.kB[Symbol.iterator]()}get count(){return this.kB.length}add(n){this.kB.push(n)}push(...n){for(const v of n)this.kB.push(v)}clear(){this.kB=[]}contains(n){return Array.contains(this.kB,n)}remove(n){return this.contains(n)?(Array.remove(this.kB,n),!0):!1}indexOf(n){return Array.indexOf(this.kB,n)}removeAt(n){if(n>=this.count)throw Error.argumentOutOfRange("index");
Array.removeAt(this.kB,n)}ga(n){if(n>=this.count)throw Error.argumentOutOfRange("index");return this.kB[n]}$(n,v){if(n>=this.count)throw Error.argumentOutOfRange("index");return this.kB[n]=v}addRange(n){for(const v of n)this.add(v)}insert(n,v){if(n>this.count)throw Error.argumentOutOfRange("index");Array.insert(this.kB,n,v)}AQc(n,v){if(n>this.count)throw Error.argumentOutOfRange("index");for(const A of v)Array.insert(this.kB,n++,A)}toArray(){return Array.clone(this.kB)}sort(){this.kB.sort()}Sc(n){this.kB.sort((v,
A)=>n(v,A))}}Object(J.a)(m,"List",null,[1720,143,1])},function(J,V,d){d(19);J.exports=d(20)},function(J,V,d){d.p=function(){function h(){for(var v=document.getElementsByTagName("script"),A=0;A<v.length;A++){var w=e(v[A].src);if(w)return w}return null}function e(v){return v.toLowerCase().endsWith("/ppteditds.precore.js")?v.substring(0,v.lastIndexOf("/")+1):null}var m=document.currentScript,n=null;if(m)n=e(m.src.split("?")[0]);else{if("undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope)return d.p;
n=h()}if(n)return n;throw"Could not locate webpack public path";}()},function(J,V,d){d.r(V);var h=d(22);const e=(u,E)=>{if(null!=E&&!Object(h.a)(u,E))throw Error.create(Sys.Res.argumentType);return E};var m=d(2);J=d(0);var n=d(4),v=d(1);class A{constructor(){this.gMa=v.a.default}S(u){u=m.Task.Create(u);u.Start$Scheduler(this.gMa);return u}SC(u,E){u=m.Task.Create(u);E.PCa?u.Z_():u.Start$Scheduler(this.gMa);return u}SO(u,E){u=m.Task.Create$object(u,E);u.Start$Scheduler(this.gMa);return u}SOC(u,E,G){u=
m.Task.Create$object(u,E);G.PCa?u.Z_():u.Start$Scheduler(this.gMa);return u}SR(u){u=n.a.C(u);u.Start$Scheduler(this.gMa);return u}SRC(u,E){u=n.a.C(u);E.PCa?u.Z_():u.Start$Scheduler(this.gMa);return u}SRO(u,E){u=n.a.CO(u,E);u.Start$Scheduler(this.gMa);return u}SROC(u,E,G){u=n.a.CO(u,E);G.PCa?u.Z_():u.Start$Scheduler(this.gMa);return u}}Object(J.a)(A,"TaskFactory",null,[]);class w extends v.a{constructor(){super()}JBe(u){window.setTimeout(()=>{this.aRe(u)},0)}}Object(J.a)(w,"DefaultTaskScheduler",v.a,
[]);J=function(u){function E(I){if(G[I])return G[I].exports;var H=G[I]={i:I,l:!1,exports:{}};u[I].call(H.exports,H,H.exports,E);H.l=!0;return H.exports}var G={};E.m=u;E.c=G;E.d=function(I,H,K){E.o(I,H)||Object.defineProperty(I,H,{enumerable:!0,get:K})};E.r=function(I){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(I,Symbol.toStringTag,{value:"Module"});Object.defineProperty(I,"__esModule",{value:!0})};E.t=function(I,H){H&1&&(I=E(I));if(H&8||H&4&&"object"===typeof I&&I&&I.A$)return I;
var K=Object.create(null);E.r(K);Object.defineProperty(K,"default",{enumerable:!0,value:I});if(H&2&&"string"!=typeof I)for(var C in I)E.d(K,C,function(Y){return I[Y]}.bind(null,C));return K};E.n=function(I){var H=I&&I.A$?function(){return I["default"]}:function(){return I};E.d(H,"a",H);return H};E.o=function(I,H){return Object.prototype.hasOwnProperty.call(I,H)};E.p="";return E(E.s=78)}({100:function(u,E,G){function I(){return C}function H(Y,M,P){C.fireEvent({level:Y,category:M,message:P})}function K(Y,
M,P){H(0,Y,function(){return"".concat(M,": ").concat(P instanceof Error?P.message:"")})}G.d(E,"c",function(){return I});G.d(E,"b",function(){return H});G.d(E,"a",function(){return K});var C=function(){var Y=[];return{fireEvent:function(M){Y.forEach(function(P){return P(M)})},addListener:function(M){M&&Y.push(M)}}}()},101:function(u,E,G){function I(Y,M,P){return{name:Y,dataType:1,value:M,classification:P?P:4}}function H(Y,M,P){return{name:Y,dataType:2,value:M,classification:P?P:4}}function K(Y,M,P){return{name:Y,
dataType:3,value:M,classification:P?P:4}}function C(Y,M,P){return{name:Y,dataType:0,value:M,classification:P?P:4}}G.d(E,"a",function(){return I});G.d(E,"c",function(){return H});G.d(E,"b",function(){return K});G.d(E,"d",function(){return C})},102:function(u,E,G){function I(){return"undefined"===typeof performance||"undefined"===typeof performance.now?0:performance.now()}function H(K){if(null!==K)return K}G.d(E,"a",function(){return I});G.d(E,"b",function(){return H})},103:function(u,E,G){G.d(E,"a",
function(){return H});var I=G(101),H=function(){function K(){this.name="Sampler";this.sampleRate=.02}K.prototype.qZf=function(C,Y){if("string"!==typeof Y||4>Y.length)return!1;for(var M=5381,P=0;P<Y.length;P++)M=(M<<5)+M+Y.charCodeAt(P);this.Pic=(M>>>0)%1E3/1E3;this.Ehh=C;return!0};K.prototype.I4k=function(C){0<=C&&1>=C&&(this.sampleRate=C)};K.prototype.Aug=function(){return void 0===this.Pic||this.Pic<this.sampleRate};K.prototype.nX=function(C){var Y=C.eventFlags.samplingPolicy;if(void 0===this.Pic||
void 0===Y)return!0;if(1===Y)return this.Aug()?(this.CBf(C,this.sampleRate,this.Pic),!0):!1;if(2===Y)return!1;this.CBf(C,1,this.Pic);return!0};K.prototype.CBf=function(C,Y,M){C.eventContract||(C.eventContract={name:"",dataFields:[]});C=C.eventContract.dataFields;C.push(Object(I.b)("Event.SampleRate",Y));C.push(Object(I.b)("Session.SamplingValue",M));this.Ehh&&C.push(Object(I.d)("Session.SamplingKey",this.Ehh));C.push(Object(I.a)("Session.MeasuresEnabled",this.Aug()))};return K}()},104:function(u,
E,G){function I(){I=Object.assign||function(H){for(var K,C=1,Y=arguments.length;C<Y;C++){K=arguments[C];for(var M in K)Object.prototype.hasOwnProperty.call(K,M)&&(H[M]=K[M])}return H};return I.apply(this,arguments)}G.d(E,"a",function(){return I})},105:function(u,E,G){function I(L){if(!L.name)throw Error("Event is missing a name");var aa=Y(L.dataFields);aa={eventName:L.name,dataFields:aa,eventFlags:{}};1===L.samplingPolicy&&(aa.eventFlags={samplingPolicy:1});return aa}function H(L){if(!L.name)throw Error("Event is missing a name");
var aa=Y(L.dataFields),Q={eventName:L.name,dataFields:aa,eventFlags:{},telemetryProperties:{dnmInterval:L.dnmInterval,dnmAllowedPartA:[]}};L.dnmAllowedPartA&&L.dnmAllowedPartA.forEach(function(ea){ea&&ea&&Q.telemetryProperties.dnmAllowedPartA.push(ea)});return Q}function K(L){if(!L.name)throw Error("Event is missing a name");null==L.succeeded&&(L.succeeded=void 0);if(null==L.durationMs||isNaN(L.durationMs))L.durationMs=0;if(null==L.count||isNaN(L.count))L.count=1;null==L.aggMode&&(L.aggMode=0);var aa=
Math.floor(1E3*L.durationMs),Q=Y(L.dataFields);aa=P.a.Vrb({rfi:L.CV||void 0,duration:aa,count:L.count,aggMode:L.aggMode,success:L.succeeded});return{eventName:L.name,eventContract:{name:P.a.SNd,dataFields:aa},dataFields:Q,eventFlags:{}}}function C(L){if(!L.name)throw Error("Event is missing a name");null==L.succeeded&&(L.succeeded=void 0);if(null==L.durationMs||isNaN(L.durationMs))L.durationMs=0;var aa=Math.floor(1E3*L.durationMs);null==L.dataFields&&(L.dataFields=[]);var Q=Y(L.dataFields),ea=P.b.Vrb({id:null==
L.actionId?void 0:L.actionId,name:null==L.actionName?void 0:L.actionName,commandSurface:null==L.commandSurface?void 0:L.commandSurface,parentName:null==L.parentName?void 0:L.parentName,triggerMethod:null==L.triggerMethod?void 0:L.triggerMethod,timeOffsetMs:null==L.timeOffsetMs?void 0:L.timeOffsetMs});Q.push.apply(Q,ea);aa=P.a.Vrb({duration:aa,count:1,aggMode:0,success:L.succeeded});return{eventName:L.name,eventContract:{name:P.a.SNd,dataFields:aa},dataFields:Q,eventFlags:{}}}function Y(L){var aa=
[];if(L)for(var Q=0;Q<L.length;Q+=1)aa.push.apply(aa,M(L[Q]));return aa}function M(L,aa){L.name||(L.name="DataFieldNameIsMissing");var Q=null!=L.string?2:null!=L.bool?1:null==L.int64||isNaN(L.int64)?null==L.double||isNaN(L.double)?null!=L.contract?6:null==L.date||isNaN(L.date)?0:5:4:3;aa=aa?aa+"."+L.name:L.name;switch(Q){case 0:return[];case 1:return[T.a(aa,L.bool)];case 2:return[T.d(aa,L.string)];case 3:return[T.c(aa,Math.floor(L.int64))];case 4:return[T.b(aa,L.double)];case 5:return[T.d(aa,(new Date(L.date)).toISOString())];
case 6:L=L.contract;Q=[];if(L.dataFields)for(var ea=0;ea<L.dataFields.length;ea+=1)Q.push.apply(Q,M(L.dataFields[ea],aa));return Q;default:throw Error(Q);}}G.d(E,"c",function(){return I});G.d(E,"b",function(){return H});G.d(E,"a",function(){return K});G.d(E,"e",function(){return C});G.d(E,"d",function(){return Y});var P=G(106),T=G(101);G(107)},106:function(u,E,G){function I(T,L,aa,Q){aa&&Q.push(Object(C.d)("".concat(T?T+"."+L:L),aa))}function H(T,L,aa,Q){"boolean"===typeof aa&&Q.push(Object(C.a)("".concat(T?
T+"."+L:L),aa))}function K(T,L,aa,Q){"number"===typeof aa&&Q.push(Object(C.c)("".concat(T?T+"."+L:L),aa))}G.d(E,"a",function(){return M});G.d(E,"b",function(){return P});var C=G(101),Y={Vrb:function(T){var L=[];K("Activity.Result","Code",T.code,L);I("Activity.Result","Type",T.type,L);K("Activity.Result","Tag",T.tag,L);H("Activity.Result","IsExpected",T.isExpected,L);L.push(Object(C.d)("zC.Activity.Result","Office.System.Result"));return L}},M={SNd:"Office.System.Activity",Vrb:function(T){var L=[];
I("Activity","CV",T.rfi,L);K("Activity","Duration",T.duration,L);K("Activity","Count",T.count,L);K("Activity","AggMode",T.aggMode,L);H("Activity","Success",T.success,L);T.result&&L.push.apply(L,Y.Vrb(T.result));L.push(Object(C.d)("zC.Activity",this.SNd));return L}},P={Vrb:function(T){var L=[];K("UserAction","Id",T.id,L);I("UserAction","Name",T.name,L);I("UserAction","CommandSurface",T.commandSurface,L);I("UserAction","ParentName",T.parentName,L);I("UserAction","TriggerMethod",T.triggerMethod,L);K("UserAction",
"TimeOffsetMs",T.timeOffsetMs,L);return L}}},107:function(u,E,G){G.d(E,"a",function(){return I});var I;(function(H){H[H.Error=10]="Error";H[H.Warning=15]="Warning";H[H.Info=50]="Info";H[H.Verbose=100]="Verbose";H[H.Spam=200]="Spam"})(I||(I={}))},108:function(u,E,G){function I(ia){return ia?[H,K,C,Y,M,T,P].map(function(ja){return ja(ia)}):[]}function H(ia){return{name:"App",contract:{name:"App",dataFields:[L("Name",ia.name),L("Platform",ia.platform),L("Version",ia.version)]}}}function K(ia){return{name:"Session",
contract:{name:"Session",dataFields:[L("Id",ia.sessionId),L("EcsETag",ia.flightsImpressionId)]}}}function C(ia){return{name:"Release",contract:{name:"Release",dataFields:[L("AudienceGroup",ia.audienceGroup)]}}}function Y(ia){return{name:"Browser",contract:{name:"Browser",dataFields:[L("Name",ia.browserName),L("Version",ia.browserVersion)]}}}function M(ia){return{name:"Culture",contract:{name:"Culture",dataFields:[L("UiLanguage",ia.appLanguage)]}}}function P(ia){return{name:"User",contract:{name:"User",
dataFields:[L("PrimaryIdentityHash",ia.loggableUserId),L("PrimaryIdentitySpace",ia.loggableUserIdSpace),L("TenantId",ia.omsTenantId),aa("IsAnonymous",ia.isAnonymousUser)]}}}function T(ia){return{name:"WAC",contract:{name:"WAC",dataFields:[L("Host",ia.host),L("ServerDocId",ia.serverDocId),L("Datacenter",ia.datacenter),aa("IsSynthetic",ia.isSynthetic),aa("IsBusinessUser",ia.isBusinessUser),aa("IsEdu",ia.isEduUser),L("ApplicationMode",ia.applicationMode),L("ApplicationModeExtended",ia.applicationModeExtended),
L("BrowserLanguage",ia.browserLanguage),L("ContentLanguage",ia.contentLanguage),L("OsVersion",ia.osVersion),L("Ring",ia.ring),L("UiHost",ia.uiHost),L("SessionOrigin",ia.sessionOrigin),L("UiHostIntegrationType",ia.uiHostIntegrationType)]}}}function L(ia,ja){return null==ja?{name:ia,string:Q}:{name:ia,string:ja}}function aa(ia,ja){return null==ja?{name:ia,bool:ea}:{name:ia,bool:ja}}G.d(E,"a",function(){return I});var Q="",ea=!1},109:function(u,E,G){function I(L){var aa={eventName:L.eventName,eventFlags:L.eventFlags||
{},telemetryProperties:L.telemetryProperties?Object(H.a)({},L.telemetryProperties):{},dataFields:L.dataFields?L.dataFields.slice():[],timestamp:L.timestamp||(new Date).getTime()};L.eventContract&&(aa.eventContract={name:L.eventContract.name,dataFields:L.eventContract.dataFields.slice()});return aa}G.d(E,"a",function(){return T});var H=G(104),K=G(110),C=G(112),Y=G(100),M=G(111),P=G(101),T=function(){function L(aa,Q,ea){var ia,ja,D;this.fIb=[];this.persistentDataFields=[];this.o9c=[];this.V6=[];this.config=
ea||{};aa&&(this.fIb=aa.fIb,(ia=this.persistentDataFields).push.apply(ia,aa.persistentDataFields),this.config=Object(H.a)(Object(H.a)({},aa.getConfig()),this.config),(ja=this.o9c).push.apply(ja,aa.o9c));Q&&(D=this.persistentDataFields).push.apply(D,Q)}L.prototype.CAf=function(aa,Q){aa.push(Object(P.c)("EventContent.Type",Q))};L.prototype.sendTelemetryEvent=function(aa){var Q=I(aa),ea=Q.telemetryProperties;ea.nexusTenantToken=-1;ea.ariaTenantToken||Object(K.a)(Q.eventName,ea)||ea.ariaTenantToken?this.Qed(Q,
1):Object(Y.b)(0,0,function(){return"No tenant token: "+aa.eventName})};L.prototype.njh=function(aa){aa=I(aa);var Q=aa.telemetryProperties,ea=Q.customerContentVersion;if(!ea||2<ea)Q.customerContentVersion=2;Q.ariaTenantToken=void 0;Q.nexusTenantToken=void 0;Q.AOa=void 0;this.CAf(aa.dataFields,2);return this.Qed(aa,2)};L.prototype.sendDirectNumericEvent=function(aa){var Q=I(aa);aa=Q.telemetryProperties;aa.AOa||Object(K.a)(Q.eventName,aa)||aa.AOa?(this.CAf(Q.dataFields,1),this.Qed(Q,3)):Object(Y.b)(0,
0,function(){return"No dnm token: "+Q.eventName})};L.prototype.Qed=function(aa,Q){if(2!==Q&&(aa.telemetryProperties.customerContentVersion||aa.telemetryProperties.customerContentType))Object(Y.b)(0,0,function(){return"Customer content"});else{try{if(0===this.fIb.length){this.config.zCl&&1E3>this.V6.length?this.V6.push([aa,Q]):Object(Y.b)(1,0,function(){return"No telemetry sinks are attached."});return}this.processTelemetryEvent(aa,Q)}catch(ea){Object(Y.a)(0,"SendTelemetryEvent",ea);return}try{this.fIb.forEach(function(ea){3===
Q||2===Q?ea.ujh&&ea.ujh(aa,Q):ea.sendTelemetryEvent(aa)})}catch(ea){}}};L.prototype.processTelemetryEvent=function(aa,Q){var ea,ia,ja;aa.dataFields&&(null===(ja=aa.dataFields)||void 0===ja?void 0:ja.unshift(Object(P.d)("OTelJS.Version",M.a)),3!==Q&&this.persistentDataFields&&(ea=aa.dataFields).unshift.apply(ea,this.persistentDataFields));0<this.o9c.length&&(Q=aa.eventContract||{name:"",dataFields:[]},(ia=Q.dataFields).push.apply(ia,this.o9c),aa.eventContract=Q);this.config.rGi||Object(C.a)(aa)};L.prototype.h1h=
function(aa){this.fIb.push(aa);this.wJc()};L.prototype.wJc=function(){var aa=this.V6;this.V6=[];if(0<this.fIb.length)for(var Q=0;Q<aa.length;Q++){var ea=aa[Q];this.Qed(ea[0],ea[1])}};L.prototype.wmh=function(aa,Q){Object(K.b)(aa,{ariaTenantToken:Q,nexusTenantToken:void 0})};L.prototype.setDNMToken=function(aa,Q){Object(K.b)(aa,{AOa:Q})};L.prototype.getConfig=function(){return this.config};return L}()},110:function(u,E,G){function I(M,P){M.substring(0,7)==="Office"+C&&M[M.length-1]!==C?Y[M]?(P.ariaTenantToken&&
(Y[M].ariaTenantToken=P.ariaTenantToken),P.AOa&&(Y[M].AOa=P.AOa)):Y[M]=P:Object(K.b)(0,0,function(){return"Namespace: ".concat(M)})}function H(M,P){for(var T=M.length;0<T;){var L=M.substr(0,T);if(Y[L])return M=Y[L],P.ariaTenantToken=M.ariaTenantToken,P.AOa=M.AOa,!0;T=M.lastIndexOf(C,T-1)}return!1}G.d(E,"b",function(){return I});G.d(E,"a",function(){return H});var K=G(100),C=".",Y={}},111:function(u,E,G){G.d(E,"a",function(){return I});var I="4.13.6"},112:function(u,E,G){function I(T){var L=T.eventName;
if(!L||L.length>Y||!M.test(L))throw Error("Invalid eventName");if(L=T.eventContract){if(L.name&&!P.test(L.name))throw Error("Invalid eventContract");H(L.dataFields)}H(T.dataFields)}function H(T){T&&T.forEach(function(L){if("string"!==typeof L.name||!P.test(L.name))throw Error("Invalid dataField name");if(2===L.dataType&&(L=L.value,"number"!==typeof L||!isFinite(L)||Math.floor(L)!==L||L<C||L>K))throw Error("Invalid integer ".concat(JSON.stringify(L)));})}G.d(E,"a",function(){return I});var K=9007199254740991,
C=-K,Y=98,M=/^Office(\.[A-Z][a-zA-Z0-9]*){2,}$/,P=/^[a-zA-Z0-9_\.]{1,95}$/},113:function(u,E,G){G.d(E,"a",function(){return I});G.d(E,"b",function(){return H});var I=[{namespace:"Office.Online",Yt:"79b56d2f6f2444f1a3d7f7c7f12bcc0c-f47f5fe6-ed89-42f6-8a43-cea0f5930b17-7407"},{namespace:"Office.Word.Online.Data",Yt:"7e7959aac92e41d6892c69a87259ed58-de5c63ef-10f5-45e1-bef2-d23e9cac2fab-6830"},{namespace:"Office.Excel.Online.Data",Yt:"011776870b754a649aedc9456ac07a97-6bd8247c-11d3-4599-b599-ec9ef6d401f6-6722"},
{namespace:"Office.PowerPoint.Online.Data",Yt:"35612b11d234460da5c673d7b172fd93-f8762c6b-96cb-4e60-87fa-015aac0c2ff1-7212"},{namespace:"Office.OneNote.Online.Data",Yt:"86258c80efed47d9b34bf77fc663b381-af82a060-b49f-448b-baf0-956ba7709592-7634"},{namespace:"Office.Visio.Online.Data",Yt:"77fd25a525d24b7f9b924307de0cc70f-5f2b6ec0-f1d2-40dd-b875-e6bd2849e1eb-7539"},{namespace:"Office.Shared.Online.Data",Yt:"4ad8b2b2029e481fb82edb7aac29de59-94494dd8-b684-4f92-ab7f-6b414eb77798-7917"},{namespace:"Office.Word.Online",
Yt:"ff7e2f12a4be407096fc01eeb760eda3-eeeb63cf-35d9-4734-ab45-66a873412359-7045"},{namespace:"Office.Excel.Online",Yt:"fad3bd1d8e4b4c06894bd7bac80e4f02-67df67b4-f1fd-4ecd-9d55-4d41540b1757-7724"},{namespace:"Office.PowerPoint.Online",Yt:"b664cab4b3f24a739be75b93b026749e-65c206a3-a985-48b4-8b50-36c56c3ce309-7201"},{namespace:"Office.OneNote.Online",Yt:"1705ef36a51840648341da866d62baf8-ddbcd60b-4ce4-48da-96be-ad5f28b48954-8035"},{namespace:"Office.Visio.Online",Yt:"a9b6cb604fe942a89c8671aab85364f6-af0f81b1-c5ce-419a-82d5-af38c33ebea3-7250"},
{namespace:"Office.Shared.Online",Yt:"d034371e26194a76a187c7108b3837ca-731725e8-1dc7-4eca-a754-b09c9d2b8dd5-6502"},{namespace:"Office.Word.Online.Health",Yt:"e064ef4d9cdb454d9eddb2f7f7a94c83-89a6d9df-7218-4efd-bcd4-16ea059deea2-7672"},{namespace:"Office.Excel.Online.Health",Yt:"e76e8055912d482eb56ea5dad2fd5a97-5552f2bb-d1eb-4843-95d7-3019215328a0-6899"},{namespace:"Office.PowerPoint.Online.Health",Yt:"706f939c0d24440ba8dfb0838ed33611-d60b1956-db23-4410-a59d-e7fa08d4217f-7388"},{namespace:"Office.OneNote.Online.Health",
Yt:"c6393e4ed4b94e3baf9a46aa6585dce0-c1b3b0c6-b44c-4121-8eae-311d31e67bb6-7176"},{namespace:"Office.Visio.Online.Health",Yt:"c4999163c49d49c99a1649b404873d24-a62a394b-ad47-45f0-92fa-fd4085dc8bb3-7324"},{namespace:"Office.Shared.Online.Health",Yt:"2800319cefba4489867c1ff30d41e7e1-ea67d761-9485-4d25-bc39-f3144e34b773-6869"},{namespace:"Office.Telemetry",Yt:"f998cc5ba4d448d6a1e8e913ff18be94-dd122e0a-fcf8-4dc5-9dbb-6afac5325183-7405"},{namespace:"Office.System",Yt:"cd836626611c4caaa8fc5b2e728ee81d-3b6d6c45-6377-4bf5-9792-dbf8e1881088-7521"},
{namespace:"Office.TellMe",Yt:"31d9dd3e4c7046a696537586281d7ed1-06d11dd6-a946-4281-8ac3-a7c2ab4776f5-7063"},{namespace:"Office.Voice",Yt:"9783945ebc2b468fbb8a2890cdab903b-787355a5-74c8-4a89-b06a-9c82635d75fa-7162"},{namespace:"Office.Insights",Yt:"250a372c4a854d8fb120ef0366f9410c-dd39bcd8-3b38-4c6c-9f8d-3821e5c28b47-7487"},{namespace:"Office.Graphics",Yt:"cfcfdb91c68c4329bb8b7cb7babb3cf7-e082c2f2-ef1d-427a-ac4d-b0b700afe7a7-7655"},{namespace:"Office.AugLoop",Yt:"3de4087d4de34817b1c376e3d1e6e293-983c4292-5ba9-485a-ab10-9797863c788b-6770"},
{namespace:"Office.FileIO",Yt:"d2b065c5ae634beb9cec4813140e22da-eda42ada-ffd9-4e26-92a1-e3b440eaf8bf-7717"},{namespace:"Office.Sandbox",Yt:"1cd66059dc1d41f1887e3770ea8ba967-f1d0108c-8535-4cf9-bf23-ec8227f6afa7-6999"},{namespace:"Office.UX",Yt:"c4388c977297413bb054bad1acf0ade1-cc58e53e-f5a4-4f37-b0d2-9a8079e34420-6879"},{namespace:"Office.Extensibility",Yt:"db334b301e7b474db5e0f02f07c51a47-a1b5bc36-1bbe-482f-a64a-c2d9cb606706-7439"}],H=[{namespace:"Office.DNM.Visio.Online",Yt:"feba3d98f7c0481c8b63754573a80618-7311e9e0-365d-4a1b-b0fb-a238e0bc7528-6955"},
{namespace:"Office.DNM.Sandbox",Yt:"b0aae8a3009047b9bf4d3b17439319b6-e96e56cc-5657-463a-a2f2-dc8c0fb9d41b-7136"}]},114:function(u,E,G){function I(P,T){Object(H.b)(P,1,function(){return"WebSink:"+T})}G.d(E,"a",function(){return M});var H=G(100),K=G(101),C=G(116),Y=G(115),M=function(){function P(T){this.K$c=[];this.stats=Object(Y.b)();this.yWe=1E3;this.m5e=500;this.Hod=100;this.Ut=[];this.enabled=!0;T&&T.NDk&&(this.m5e=T.NDk)}P.prototype.init=function(T,L){if(!T.endpointUrl||!L.uuid||!L.zfg)return this.enabled=
!1,I(0,2),!1;T.uploadFrequency&&(this.yWe=T.uploadFrequency);T.batchSize&&(this.Hod=T.batchSize);this.Fzd=T;this.xyf=L;return!0};P.prototype.isInitialized=function(){if(this.enabled){if(this.Fzd)return!0;I(1,1)}return!1};P.prototype.wck=function(T){var L=this;Object.keys(T).forEach(function(aa){Object(Y.c)(L.stats[aa])?Object(Y.c)(T[aa])?L.stats[aa]+=T[aa]:L.stats[aa]=T[aa]:aa==="wr".toString()&&Object.keys(T.wr).forEach(function(Q){L.stats.wr[Q]=L.stats.wr[Q]+T.wr||T.wr[Q]})})};P.prototype.Zgl=function(){var T=
this;if(this.isInitialized()){this.stats.s=1;try{this.eSb=this.xyf.zfg(),this.eSb.addEventListener("message",function(L){L=L.data;switch(L.t){case 1:T.hmj();break;case 4:T.wck(L.d);break;case 5:I(1,L.d);break;default:I(1,14)}}),this.eSb.addEventListener("error",function(){I(1,12);1===T.stats.s&&T.J1f()}),this.eSb.addEventListener("errormessage",function(){I(1,13)})}catch(L){I(1,10),this.J1f()}}};P.prototype.hmj=function(){this.isInitialized()&&(this.stats.s=2,Object(H.b)(2,1,function(){return"WebSink:Loaded"}),
this.eSb.postMessage({t:2,d:this.Fzd}),this.wJc())};P.prototype.J1f=function(){this.stats.s=4;this.shutdown(!1)};P.prototype.wJc=function(){var T=Object(Y.a)(),L=this.stats,aa=this.Ut.slice(0,this.Hod),Q=aa.length;this.Ut=this.Ut.slice(this.Hod);try{Q&&(L.pw+=Q,this.eSb.postMessage({t:3,d:aa}))}catch(ea){I(1,11)}finally{T=Object(Y.a)()-T,L.md+=T,T>=L.mm&&(L.mm=T,L.mn=Q),this.Hvc&&clearTimeout(this.Hvc),this.Hvc=setTimeout(this.wJc.bind(this),this.yWe)}};P.prototype.nze=function(T,L){for(var aa=0;aa<
this.K$c.length;aa++){var Q=this.K$c[aa],ea=Q.name,ia=!1;if(3!==L||"EventThrottler"===ea){var ja=Object(Y.a)();try{ia=Q.nX(T)}catch(D){}Q=Object(Y.a)()-ja;this.stats.pd[ea]=this.stats.pd[ea]+Q||Q;if(!ia)return this.stats.po[ea]=this.stats.po[ea]+1||1,!1}}T.dataFields.push(Object(K.d)("OTelJS.Sink","WebSink"));return!0};P.prototype.HBe=function(T){2===this.stats.s||this.Ut.length<this.m5e?(this.stats.q+=1,this.Ut.push(T)):(I(1,3),this.stats.s=3,this.shutdown(!1))};P.prototype.sendTelemetryEvent=function(T){this.enabled&&
this.nze(T,1)&&this.HBe({event:T,t:1})};P.prototype.njh=function(T){this.enabled&&this.nze(T,2)&&this.HBe({event:T,t:2})};P.prototype.ujh=function(T,L){this.enabled&&this.nze(T,L)&&this.HBe({event:T,t:L})};P.prototype.shutdown=function(T){if(this.isInitialized())try{this.stats.pm=this.Ut.length,C.a(this.Fzd,{uuid:this.xyf.uuid,Bxl:T,stats:this.stats},this.Ut),this.Ut=[]}catch(L){I(1,30)}this.enabled=!1;this.Hvc&&clearTimeout(this.Hvc)};return P}()},115:function(u,E,G){function I(){var C;return C=
{},C.md=0,C.mm=0,C.mn=0,C.q=0,C.po={},C.pw=0,C.wa=0,C.wp=0,C.wd=0,C.wr={},C.ws=0,C.pm=0,C.sp=0,C.ss=0,C.sd=0,C.pd={},C.d=0,C.b=0,C.s=0,C}function H(){return Date.now()}function K(C){return"number"===typeof C}G.d(E,"c",function(){return K});G.d(E,"a",function(){return H});G.d(E,"b",function(){return I});"object"===typeof window&&"object"===typeof window.performance&&"function"===typeof window.performance.now&&(H=function(){return window.performance.now()})},116:function(u,E,G){function I(cb,Za,va){function Fa(Bb,
Eb,tb,Yb){var Tc,ib=Eb,Zb=0;if("undefined"!==typeof ib&&""!==ib){Object(L.c)(Eb)&&(Zb=6);switch(tb){case 3:Zb=6;break;case 2:Zb=4;break;case 4:Zb=8;break;case ia:Zb=9;break;case 0:ib="string"===typeof ib?ib.substr(0,25E3):ib}if(Nb){Eb=Yb.data;Yb=Yb.ext.metadata;for(tb=0;tb<Bb.length-1;){var Cc=Bb[tb];if(!Cc)return;if(Eb[Cc]){if("object"!==typeof Eb)return}else Eb[Cc]={};Eb=Eb[Cc];if(Zb){var ob=Yb.f||{};ob[Cc]||(ob[Cc]={});Yb.f=ob;Yb=ob[Cc]}tb++}Bb=Bb[tb];"object"===typeof Eb&&"object"!==typeof Eb[Bb]&&
(Eb[Bb]=ib,Zb&&(Yb.f=Object(M.a)(Object(M.a)({},Yb.f),(Tc={},Tc[Bb]={t:Zb},Tc))))}else Tc=Bb.join(qa),Yb.data[Tc]=Eb,Zb&&(Yb.ext.metadata.f[Tc]={t:Zb})}}function Ca(Bb,Eb,tb){Bb&&Bb.forEach(function(Yb){var Tc=Yb.classification;if(4===Tc||1===Tc)Tc=Yb.name.split(qa),Tc[0]!==D&&(Eb&&Tc.unshift(ja),Fa(Tc,Yb.value,Yb.dataType,tb))})}var La,nb,Nb=!0===(null===(nb=null===(La=cb.extensionConfig)||void 0===La?void 0:La.PostChannel)||void 0===nb?void 0:nb.enableCompoundKey),Rb=[],Ya={},Qb=Za.uuid();La=cb.minSinkLimit;
La=Object(L.c)(La)?La:aa;va=va.slice(0,La);var bb=Za.stats.pw+1;va.forEach(function(Bb){var Eb=Bb.event.telemetryProperties.ariaTenantToken;a:{var tb=bb;if(1===Bb.t){Bb=Bb.event;var Yb=Bb.timestamp,Tc=(Yb?new Date(Yb):new Date).toISOString();Yb=Bb.eventFlags.diagnosticLevel;if(cb.enableOptionalEvents||10===Yb||110===Yb||120===Yb){var ib=Bb.eventName;Yb={name:ib,time:Tc,ver:"4.0",iKey:"o:"+Eb.substr(0,32),ext:{sdk:{seq:tb},metadata:{f:{}}},data:{}};Fa([pa,za],Ja,0,Yb);Fa(["baseData","properties","version"],
xa+"="+T.a,0,Yb);Ca(cb.persistentDataFields,!1,Yb);Fa([pa,Z],ib,0,Yb);Fa([pa,oa],tb,2,Yb);Fa([pa,Ba],Tc,ia,Yb);Fa([pa,Ma],Qb+qa+tb,0,Yb);tb="custom";if(Tc=Bb.eventContract)ib=Tc.name,Fa([pa,ka],ib,0,Yb),tb+=qa+ib.toLowerCase().replace(/\./g,"_"),Ca(Tc.dataFields,!1,Yb);Yb.data.baseType=tb;Ca(Bb.dataFields,!0,Yb);Bb=Yb;break a}}Bb=void 0}Bb&&(Rb.push(Bb),Ya[Eb]=!0,bb+=1)});return[Rb,Object.keys(Ya)]}function H(cb,Za,va){for(var Fa="",Ca="",La=0;La<cb.length;La++){Ca=Fa+Ca+JSON.stringify(cb[La]);if(Ca.length>
Za)break;Fa=Ca;va.sp+=1;Ca=sa}return Fa}function K(cb,Za,va){Za=H(Za,ea,va);var Fa=new XMLHttpRequest;Fa.onload=function(){var Ca=Fa.responseText;Ca&&(Ca=JSON.parse(Ca),Ca.uYh&&(va.ss+=parseInt(Ca.uYh,10)),Ca.HMk&&(va.sd+=parseInt(Ca.HMk,10)))};Fa.onerror=function(){va.sd=va.sp};Fa.open(na,cb);Fa.send(Za)}function C(cb,Za,va){var Fa=Za.length;if(null===navigator||void 0===navigator?0:navigator.sendBeacon){var Ca=H(Za,Q,va);if(navigator.sendBeacon(cb,Ca))va.ss=va.sp;else{for(Ca=0;Ca<Fa;){var La=JSON.stringify(Za[Ca]);
if(!navigator.sendBeacon(cb,La))break;Ca++}va.ss=Ca;va.sd=va.sp-Ca}}else va.sd=Fa}function Y(cb,Za,va){if(Ha)Object(P.b)(0,1,function(){return Ga+20});else try{var Fa=I(cb,Za,va),Ca=Fa[0],La=Fa[1];if(0!==Ca.length&&0!==La.length){var nb=cb.endpointUrl+"?cors=true&content-type=application/x-json-stream&apikey="+La.join(),Nb=Za.stats;Za.Bxl?C(nb,Ca,Nb):K(nb,Ca,Nb);Ha=!0}}catch(Rb){Object(P.b)(0,1,function(){return Ga+22})}}G.d(E,"a",function(){return Y});var M=G(104),P=G(100),T=G(117),L=G(115),aa=500,
Q=65536,ea=4194304,ia="dt",ja="Data",D="zC",pa="Event",Z="Name",oa="Sequence",Ba="Time",Ma="Id",za="Source",ka="Contract",qa=".",Ja="OTelJS",xa=Ja+"Min",Ga=xa+":",na="POST",sa="\n",Ha=!1},117:function(u,E,G){G.d(E,"a",function(){return I});var I="4.13.6"},78:function(u,E,G){G.r(E);var I=G(92);G.d(E,"TelemetryFactoryGlobal",function(){return I.a});var H=G(95);G.d(E,"logUserAction",function(){return H.f});G.d(E,"logActivity",function(){return H.d});G.d(E,"ScorecardAggregateMethod",function(){return H.a});
G.d(E,"logActivityForExperiment",function(){return H.e});G.d(E,"sendTelemetryEvent",function(){return H.o});G.d(E,"sendActivityEvent",function(){return H.i});G.d(E,"sendDirectNumericEvent",function(){return H.j});G.d(E,"sendOtelEvent",function(){return H.n});G.d(E,"sendOtelCustomerContent",function(){return H.l});G.d(E,"sendOtelDirectNumeric",function(){return H.m});G.d(E,"sendUserActionEvent",function(){return H.p});G.d(E,"addNamespaceMapping",function(){return H.b});G.d(E,"setDNMToken",function(){return H.q});
G.d(E,"flushAsync",function(){return H.c});G.d(E,"setEnabledState",function(){return H.r});G.d(E,"registerShutdownHook",function(){return H.h});G.d(E,"shutdown",function(){return H.s});G.d(E,"registerEventHandler",function(){return H.g});G.d(E,"sendEventDirectlyToHandler",function(){return H.k});var K=G(96);G.d(E,"disableSessionLevelTelemetry",function(){return K.a});G.d(E,"setWorkerEnabledState",function(){return K.b});G.d(E,"startOtelWorker",function(){return K.c})},92:function(u,E,G){G.d(E,"a",
function(){return I});var I=new (G(93).a)},93:function(u,E,G){G.d(E,"a",function(){return H});var I=G(94),H=function(){function K(){}K.prototype.createInstance=function(){return new I.a};return K}()},94:function(u,E,G){G.d(E,"a",function(){return C});var I=G(95),H=G(96),K=G(102),C=function(){function Y(){}Y.prototype.sendTelemetryEvent=function(M){M&&Object(I.o)(M)};Y.prototype.sendDirectNumericEvent=function(M){M&&Object(I.j)(M)};Y.prototype.sendActivityEvent=function(M){M&&Object(I.i)(M)};Y.prototype.sendUserActionEvent=
function(M){M&&Object(I.p)(M)};Y.prototype.addNamespaceMapping=function(M,P){M&&P&&Object(I.b)(M,P)};Y.prototype.setDNMToken=function(M,P){M&&P&&Object(I.q)(M,P)};Y.prototype.sendOtelEvent=function(M){M&&Object(I.n)(M)};Y.prototype.sendOtelCustomerContent=function(M){M&&Object(I.l)(M)};Y.prototype.sendOtelDirectNumeric=function(M){M&&Object(I.m)(M)};Y.prototype.setEnabledState=function(M){Object(I.r)(M)};Y.prototype.registerEventHandler=function(M){M&&Object(I.g)(M)};Y.prototype.shutdown=function(){return Object(I.s)()};
Y.prototype.setOtelWorkerEnabledState=function(M,P){return Object(H.b)(M,Object(K.b)(P))};Y.prototype.startOtelWorker=function(){return Object(H.c)()};return Y}()},95:function(u,E,G){function I(na,sa,Ha,cb,Za,va,Fa){aa({name:null,actionName:na,commandSurface:Za,parentName:Ha,triggerMethod:cb,durationMs:va,succeeded:sa,dataFields:Fa})}function H(na,sa,Ha,cb){void 0===sa&&(sa=!0);void 0===Ha&&(Ha=0);void 0===cb&&(cb=[]);Y({name:na,succeeded:sa,durationMs:Ha,dataFields:cb})}function K(na,sa,Ha,cb,Za,
va,Fa){void 0===Ha&&(Ha=Ga.Count);void 0===cb&&(cb=!0);void 0===Za&&(Za=0);void 0===va&&(va=[]);void 0===Fa&&(Fa=!1);if(null!==na&&void 0!==na&&""!==na){var Ca=sa;if(null===sa||void 0===sa)if(Ha===Ga.Count)Ca=1;else return;va.push({name:"WAC_Experiment",string:Ha.toString()});va.push({name:"WAC_Experiment_Value",double:Ca});va.push({name:"WAC_Experiment_EventName",string:"WAC_Exp_"+na+"_"+Ha.toString()});va.push({name:"WAC_Experiment_AggregateOnlySucceeded",bool:Fa});Y({name:na,succeeded:cb,durationMs:Za,
dataFields:va})}}function C(na){oa({kind:"event",event:na,timestamp:(new Date).getTime()})}function Y(na){oa({kind:"activity",event:na,timestamp:(new Date).getTime()})}function M(na){oa({kind:"dnm",event:na,timestamp:(new Date).getTime()})}function P(na){oa({kind:"otel",event:na})}function T(na){oa({kind:"otelcc",event:na})}function L(na){oa({kind:"oteldnm",event:na})}function aa(na){oa({kind:"action",event:na,timestamp:(new Date).getTime()})}function Q(na,sa){oa({kind:"addNamespaceMapping",namespace:na,
ariaTenantToken:sa})}function ea(na,sa){oa({kind:"setDNMToken",namespace:na,ariaTenantToken:sa})}function ia(){oa({kind:"flush"})}function ja(na){(Ma=na)||(za=[])}function D(na){Ja=na}function pa(){Ja&&Ja();oa({kind:"shutdown"});return za.length+qa}function Z(na){ka=na;za.forEach(function(sa){return oa(sa)});za=[]}function oa(na){Ma&&(ka?ka(na):za.length<=xa?za.push(na):qa+=1)}function Ba(na){ka&&ka(na)}G.d(E,"f",function(){return I});G.d(E,"d",function(){return H});G.d(E,"a",function(){return Ga});
G.d(E,"e",function(){return K});G.d(E,"o",function(){return C});G.d(E,"i",function(){return Y});G.d(E,"j",function(){return M});G.d(E,"n",function(){return P});G.d(E,"l",function(){return T});G.d(E,"m",function(){return L});G.d(E,"p",function(){return aa});G.d(E,"b",function(){return Q});G.d(E,"q",function(){return ea});G.d(E,"c",function(){return ia});G.d(E,"r",function(){return ja});G.d(E,"h",function(){return D});G.d(E,"s",function(){return pa});G.d(E,"g",function(){return Z});G.d(E,"k",function(){return Ba});
var Ma=!1,za=[],ka,qa=0,Ja,xa=2E4,Ga;(function(na){na.Count="Count";na.Avg="Avg";na.Sum="Sum"})(Ga||(Ga={}))},96:function(u,E,G){function I(){ka=!1}function H(){if(!Ma||!Ba)return{succeeded:!1,failureReason:"NotEnabled"};Object(pa.h)(function(){});var Ga=Ba();if(!Ga)return{succeeded:!1,failureReason:"NoSettings"};if(!Ga.ulsLoggingMethods||!Ga.ulsLoggingMethods.sendTraceTag)return{succeeded:!1,failureReason:"ULSLoggingMethods"};var na=Ga.ulsLoggingMethods.sendTraceTag;if(oa)return Object(Z.c)("WebSinkAlreadyInitialized",
na);var sa=Ga.workerUrl;if(!sa)return Object(Z.c)("WorkerUrl",na);var Ha=Ga.telemetryLoggerSettings;if(!Ha)return Object(Z.c)("TelemetrySettings",na);var cb=Ha.ariaEndpointUrl;if(!Ha.ariaEndpointUrl)return Object(Z.c)("AriaUrl",na);var Za=Ha.alwaysOnMetadata;if(!Za)return Object(Z.c)("AlwaysOnMetadata",na);if(!Ga.uuid)return Object(Z.c)("Uuid",na);Ga.batchSize&&(qa.WDh=Ga.batchSize);Object(aa.c)().addListener(T);Ha.enableCustomerContent&&(za=!0);M(Za,na);Za=Object(L.d)(Object(ja.a)(Za));for(var va=
new Q.a(void 0,void 0,{rGi:!0}),Fa=0,Ca=ia.a;Fa<Ca.length;Fa++){var La=Ca[Fa];va.wmh(La.namespace,La.Yt)}Fa=0;for(Ca=ia.b;Fa<Ca.length;Fa++)La=Ca[Fa],va.setDNMToken(La.namespace,La.Yt);var nb=new ea.a;nb.init({endpointUrl:cb,persistentDataFields:Za,enableOptionalEvents:!0,extensionConfig:{PostChannel:{enableCompoundKey:!0}},enableCustomerContent:Object(D.b)(Ha.enableCustomerContent),minSinkLimit:Ga.minSinkLimit,batchSize:Object(D.b)(Ga.batchSize),uploadFrequency:Object(D.b)(Ga.batchFrequencyMs),custom:{enableDNM:Object(D.b)(Ha.enableDNM)}},
{uuid:Ga.uuid,zfg:function(){var Nb=new Blob(["try{importScripts('".concat(encodeURI(sa),'\');}catch(e){self.postMessage("Error loading Worker script")}')],{type:"application/javascript"});return new Worker(URL.createObjectURL(Nb))}});Ha.samplingIsEnabled&&(Object(Z.b)(nb,Ha)||na(541411083,226,15,"Could not enable sampler"));va.h1h(nb);oa={oag:function(){return va},U1d:function(){return nb},getSettings:function(){return Ga},sendTraceTag:na};Object(pa.g)(function(Nb){K(Nb)});return{succeeded:!0}}function K(Ga){if(oa){oa.sendTraceTag(541411082,
226,50,"SendToWorkerApi with "+Ga.kind);var na=Object(D.a)(),sa=void 0,Ha=oa.oag(),cb=Ha.sendTelemetryEvent.bind(Ha);switch(Ga.kind){case "addNamespaceMapping":Ha.wmh(Ga.namespace,Ga.ariaTenantToken);return;case "setDNMToken":Ha.setDNMToken(Ga.namespace,Ga.ariaTenantToken);return;case "flush":return;case "shutdown":cb=oa.U1d().stats;ka&&Object(Z.d)(cb,qa,oa.oag());oa.U1d().shutdown(!0);ka&&Object(Z.e)(cb,qa,oa.sendTraceTag);return;case "event":sa=P(Object(L.c)(Ga.event),Ga);break;case "dnm":sa=P(Object(L.b)(Ga.event),
Ga);cb=Ha.sendDirectNumericEvent.bind(Ha);break;case "action":sa=Ga.event;null==sa.name&&(sa.name=Ja,null!=sa.actionName&&(sa.name+=sa.actionName));sa=Object(L.e)(sa);sa=P(sa,Ga);break;case "activity":sa=Ga.event;null==sa||null==sa.name||0<=sa.name.indexOf("Office.")||(sa.name=xa+sa.name);sa=Object(L.a)(sa);sa=P(sa,Ga);break;case "otel":sa=Ga.event.otelEvent;break;case "otelcc":za&&(sa=Ga.event.otelEvent,cb=Ha.njh.bind(Ha));break;case "oteldnm":sa=Ga.event.otelEvent;cb=Ha.sendDirectNumericEvent.bind(Ha);
break;default:Ga}sa&&(Ga=Object(D.a)()-na,na=Object(D.a)(),cb(sa),cb=Object(D.a)()-na,qa.conversionDurationMs+=Ga,qa.logDurationMs+=cb,qa.processed+=1)}}function C(Ga,na){Ga&&na?(Ma=!0,Ba=na,Object(pa.h)(function(){return H()})):(Ma=!1,Ba=void 0)}function Y(){var Ga=H();if(!Ga.succeeded)return Ga;var na=oa.U1d();na.Zgl();var sa=oa.getSettings().telemetryLoggerSettings;Object(Z.a)(na,sa);return Ga}function M(Ga,na){Ga.name?(Ja="Office.".concat(Ga.name,".Online.UserAction."),xa="Office.".concat(Ga.name,
".Online.Data.Activity.")):na(541411084,226,100,"Cannot determine the App for UserActionEvent, using generic UserAction event name.")}function P(Ga,na){Ga.timestamp=na.timestamp;return Ga}function T(Ga){if(oa){var na=Ga.message(),sa=50,Ha=Ga.level;0===Ha?sa=10:1===Ha&&(sa=15);1===Ga.category&&"WebSink"===na.substring(0,7)&&oa.sendTraceTag(540657436,226,sa,na)}}G.d(E,"a",function(){return I});G.d(E,"b",function(){return C});G.d(E,"c",function(){return Y});var L=G(105),aa=G(100),Q=G(109),ea=G(114),
ia=G(113),ja=G(108),D=G(102),pa=G(95),Z=G(97);(function(){throw Error();});var oa,Ba,Ma=!1,za=!1,ka=!0,qa={processed:0,conversionDurationMs:0,logDurationMs:0,WDh:0},Ja="Office.Online.UserAction",xa="Office.Online.Data.Activity"},97:function(u,E,G){function I(Q,ea){if(ea.wacAriaThrottlingIsEnabled){var ia=new T.a("WebSink",Q);ia.i5k(Object(aa.b)(ea.wacAriaSingleEventThrottlePerSec));ia.g6k(Object(aa.b)(ea.wacAriaTotalEventsThrottlePerSec));(ea=ea.otelEventNamesToBeSuppressedCommaSeparated)&&ea.split(",").forEach(function(ja){ia.q3k(ja)});
Q.K$c.push(ia)}}function H(Q,ea){var ia=ea.alwaysOnMetadata;if(!ia)return!1;var ja=ia.loggableUserId;ia=ia.sessionId;ea=ea.sampleRate;if("number"===typeof ea){var D=new L.a;D.I4k(ea);if(ja&&D.qZf("PrimaryIdentityHash",ja)||ia&&D.qZf("SessionId",ia))return Q.K$c.push(D),!0}return!1}function K(Q,ea,ia){Q=JSON.stringify(Object(M.a)(Object(M.a)({},ea),Q));ia(526513554,226,50,Q)}function C(Q,ea,ia){ea={eventName:"Office.Online.Telemetry.OTelJS.WebSink.Session.Stats",dataFields:[Object(P.c)("Queued",Q.q),
Object(P.c)("PassedToWebWorker",Q.pw),Object(P.c)("WebWorkerAccepted",Q.wa),Object(P.c)("WebWorkerProcessed",Q.wp),Object(P.c)("WebWorkerDropped",Q.wd),Object(P.c)("WebWorkerSent",Q.ws),Object(P.b)("MessagingDurationMs",Q.md),Object(P.b)("MaxMessagingDurationMs",Q.mm),Object(P.c)("MaxMessagingDurationNumEvents",Q.mn),Object(P.c)("WebSinkBatchSize",ea.WDh),Object(P.b)("WebWorkerProcessingDurationMs",Q.d),Object(P.b)("ConversionDurationMs",ea.conversionDurationMs),Object(P.b)("LogDurationMs",ea.logDurationMs),
Object(P.c)("Bytes",Q.b),Object(P.c)("WebWorkerStatus",Q.s)],eventFlags:{samplingPolicy:191,diagnosticLevel:110}};if(Q.po)for(var ja in Q.po)"EventThrottler"!==ja&&"Sampler"!==ja&&"DiagnosticLevel"!==ja||ea.dataFields.push(Object(P.c)("PreprocessedOut."+ja,Q.po[ja]));ia.sendTelemetryEvent(ea)}function Y(Q,ea){ea(526513555,226,15,"Failed to initialize worker because "+Q);return{succeeded:!1,failureReason:Q}}G.d(E,"a",function(){return I});G.d(E,"b",function(){return H});G.d(E,"e",function(){return K});
G.d(E,"d",function(){return C});G.d(E,"c",function(){return Y});var M=G(104),P=G(101),T=G(98),L=G(103),aa=G(102)},98:function(u,E,G){G.d(E,"a",function(){return C});var I=G(101),H=G(100),K=G(99),C=function(){function Y(M,P){this.rVh=M;this.uwf=P;this.name="EventThrottler";this.FDd=0;this.$Qb={};this.s1e={};this.Nbf=Date.now();this.Uwd={}}Y.prototype.i5k=function(M){this.wdf=M};Y.prototype.g6k=function(M){this.Adf=M};Y.prototype.q3k=function(M){this.Uwd[M]=0};Y.prototype.nX=function(M){M=M.eventName;
if("Office.Telemetry.OTelJS.EventThrottled"===M)return!0;var P=!0;1E3<Date.now()-this.Nbf&&(this.Nbf=Date.now(),this.FDd=0,this.$Qb={});this.$Qb[M]=this.$Qb[M]+1||1;M in this.Uwd?P=this.jId(this.$Qb[M],this.Uwd[M],"MaxNamedEventsPerSecond",M):"number"===typeof this.wdf&&(P=this.jId(this.$Qb[M],this.wdf,"MaxSingleEventsPerSecond",M));"number"===typeof this.Adf&&(this.FDd++,P&&(P=this.jId(this.FDd,this.Adf,"MaxTotalEventsPerSecond",M)));return P};Y.prototype.jId=function(M,P,T,L){return M>P?(M===P+
1&&this.uwf&&!this.s1e[L]&&(this.s1e[L]=!0,this.uwf.sendTelemetryEvent({eventName:"Office.Telemetry.OTelJS.EventThrottled",telemetryProperties:{ariaTenantToken:K.a,nexusTenantToken:1723},eventFlags:{diagnosticLevel:110},dataFields:[Object(I.d)("SinkName",this.rVh||""),Object(I.d)("ThrottledEvent.Name",L),Object(I.c)(T,P)]})),Object(H.b)(2,1,function(){return"1DS Sink Event Throttle: Exceeded ".concat(P," ").concat(T,": ").concat(L)}),!1):!0};return Y}()},99:function(u,E,G){G.d(E,"a",function(){return I});
G(100);var I="f998cc5ba4d448d6a1e8e913ff18be94-dd122e0a-fcf8-4dc5-9dbb-6afac5325183-7405"}});V=window.dynamicScriptLoaderDependencies=[{identifier:"appChrome",dependencies:["common"]},{identifier:"sharedComments",dependencies:["common","common50","comment-pane-strings"]},{identifier:"floatingContainerManager",dependencies:["common","common50"]},{identifier:"versionHistory",dependencies:["common","common50","office-version-history-strings","friendly-dates-strings","version-history-sprite"]},{identifier:"colorPickerManager",
dependencies:["common","common50"]},{identifier:"selectionPaneManager",dependencies:["common","common50"]},{identifier:"headerFooterManager",dependencies:["common","common50"]},{identifier:"taskPanes",dependencies:["common","common50"]},{identifier:"liveActor",dependencies:["common","common50","powerpoint-live-strings","office-common-strings"]},{identifier:"immersiveReader",dependencies:["common"]},{identifier:"slideshowToolbar",dependencies:["common","common50","powerpoint-slideshow-toolbar-strings"]},
{identifier:"inkButton",dependencies:["common","common50","powerpoint-slideshow-toolbar-strings"]},{identifier:"rehearsalSummaryPage",dependencies:["common","common50","powerpoint-presenter-coach-strings"]},{identifier:"voiceUI",dependencies:["common","common50"]},{identifier:"catchUpActivity",dependencies:["common","common50","powerpoint-catchup-activity-intl"]},{identifier:"agendaConverter",dependencies:["common","common50","office-common-strings","powerpoint-agenda-to-ppt-strings"]},{identifier:"audioPlayback",
dependencies:["common"]},{identifier:"powerpoint-ribbon-intl",isLocalized:!0},{identifier:"ppt-ribbon-sprite-lazy",isLocalized:!0},{identifier:"powerpoint-editor-intl",isLocalized:!0},{identifier:"ppt-editor-sprite",isLocalized:!0},{identifier:"ppt-ribbon-sprite-ext",isLocalized:!0},{identifier:"comment-pane-strings",isLocalized:!0},{identifier:"office-version-history-strings",isLocalized:!0},{identifier:"friendly-dates-strings",isLocalized:!0},{identifier:"version-history-sprite",isLocalized:!0},
{identifier:"tellme-strings",isLocalized:!0},{identifier:"powerpoint-live-strings",isLocalized:!0},{identifier:"powerpoint-presenter-coach-strings",isLocalized:!0},{identifier:"powerpoint-agenda-to-ppt-strings",isLocalized:!0},{identifier:"office-common-strings",isLocalized:!0},{identifier:"powerpoint-slideshow-toolbar-strings",isLocalized:!0},{identifier:"accessibility-checker-pane-strings",isLocalized:!0},{identifier:"audio-settings-strings",isLocalized:!0},{identifier:"powerpoint-discoverability-strings",
isLocalized:!0},{identifier:"powerpoint-ribbon-mlr-intl",isLocalized:!0},{identifier:"ppt-ribbon-mlr-sprite-lazy",isLocalized:!0},{identifier:"ppt-ribbon-mlr-sprite",isLocalized:!0},{identifier:"ppt-ribbon-sprite",isLocalized:!0},{identifier:"powerpoint-ribbon-intl-lazy",isLocalized:!0},{identifier:"powerpoint-ribbon-mlr-intl-lazy",isLocalized:!0},{identifier:"powerpoint-catchup-activity-intl",isLocalized:!0}];var y=function(u){function E(I){if(G[I])return G[I].exports;var H=G[I]={i:I,l:!1,exports:{}};
u[I].call(H.exports,H,H.exports,E);H.l=!0;return H.exports}var G={};E.m=u;E.c=G;E.d=function(I,H,K){E.o(I,H)||Object.defineProperty(I,H,{enumerable:!0,get:K})};E.r=function(I){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(I,Symbol.toStringTag,{value:"Module"});Object.defineProperty(I,"__esModule",{value:!0})};E.t=function(I,H){H&1&&(I=E(I));if(H&8||H&4&&"object"===typeof I&&I&&I.A$)return I;var K=Object.create(null);E.r(K);Object.defineProperty(K,"default",{enumerable:!0,
value:I});if(H&2&&"string"!=typeof I)for(var C in I)E.d(K,C,function(Y){return I[Y]}.bind(null,C));return K};E.n=function(I){var H=I&&I.A$?function(){return I["default"]}:function(){return I};E.d(H,"a",H);return H};E.o=function(I,H){return Object.prototype.hasOwnProperty.call(I,H)};E.p="";return E(E.s="./lib/index.js")}({"../../.store/toposort@1.0.7-e70287510c5359da9183/node_modules/toposort/index.js":function(u){function E(G,I){function H(P,T,L){if(0<=L.indexOf(P)){try{var aa=", node was:"+JSON.stringify(P)}catch(ea){aa=
""}throw Error("Cyclic dependency"+aa);}if(!~G.indexOf(P))throw Error("Found unknown node. Make sure to provided all involved nodes. Unknown node: "+JSON.stringify(P));if(!Y[T]){Y[T]=!0;aa=I.filter(function(ea){return ea[0]===P});if(T=aa.length){L=L.concat(P);do{var Q=aa[--T][1];H(Q,G.indexOf(Q),L)}while(T)}C[--K]=P}}for(var K=G.length,C=Array(K),Y={},M=K;M--;)Y[M]||H(G[M],M,[]);return C}u.exports=function(G){for(var I=[],H=0,K=G.length;H<K;H++){var C=G[H];0>I.indexOf(C[0])&&I.push(C[0]);0>I.indexOf(C[1])&&
I.push(C[1])}return E(I,G)};u.exports.BTb=E},"./lib/DynamicScriptLoader.js":function(u,E,G){Object.defineProperty(E,"__esModule",{value:!0});E.DynamicScriptLoader=void 0;var I=G("./lib/getOrderedScriptAndDependencies.js"),H=G("./lib/loadScript.js"),K=G("./lib/preloadScript.js");u=function(){function C(Y){var M=this;this.config=Y;this.kfh=new Map;this.Ovb=new Map;this.xdd=new Map;this.loadScript=function(P){var T=M.config,L=T.crossOriginAttributeValue,aa=T.loadScriptHandler,Q=T.loadScriptWithRetryHandler,
ea=(0,I.q_d)(P,M.Ovb);T=ea.map(function(ia){var ja=M.kfh.get(ia);ja||(ja=(Q||aa||H.loadScript)(ia,M.L1d(ia),L,void 0,void 0,M.Mdg(ia)),M.kfh.set(ia,ja));return ja});return M.config.isRetryEnabled?Promise.all(T).then(function(){return P},function(){ea.forEach(function(ia,ja){var D=M.xdd.get(ia);D||(D=(0<ja?M.xdd.get(ea[ja-1]):Promise.resolve()).then(function(){return(Q||aa||H.loadScript)(ia,M.L1d(ia),L,5,!0,M.Mdg(ia))}),M.xdd.set(ia,D))});return M.xdd.get(ea[ea.length-1]).then(function(){return P})}):
Promise.all(T).then(function(){return P})};this.preloadScript=function(P){(0,I.q_d)(P,M.Ovb).forEach(function(T){return(0,K.preloadScript)(M.L1d(T),M.config.crossOriginAttributeValue)})};Y.knownScripts&&Y.knownScripts.forEach(function(P){var T=P.identifier.toLowerCase();if(M.Ovb.has(T))throw Error("The knownScripts passed into the DynamicScriptLoader config contains multiple entries for the script with identifier: ".concat(T));M.Ovb.set(T,P)})}C.prototype.getConfig=function(){return this.config};
C.prototype.Mdg=function(Y){Y=this.Ovb.get(Y)||{identifier:Y};return this.config.resolveSriHash?this.config.resolveSriHash(Y):""};C.prototype.L1d=function(Y){Y=this.Ovb.get(Y)||{identifier:Y};return this.config.resolveScript(Y)};return C}();E.DynamicScriptLoader=u},"./lib/appResourceLoader.js":function(u,E,G){Object.defineProperty(E,"__esModule",{value:!0});E.dyi=E.dUj=E.init=void 0;var I=G("./lib/loadScript.js"),H=!1,K,C;E.init=function(M,P,T){K=M;C=T;G.p=P;H=!0};E.dUj=function(M,P){P=K(M,P);return(0,
I.loadScript)(M,P,"anonymous",5)};var Y=new Map;E.dyi=function(M,P){return function aa(L){if(!H)throw Error("appResourceLoader not initialized");if(Y.has(L))return Y.get(L);var Q=Date.now(),ea=-1,ia=[];if(M[L]&&M[L].dependencies)for(var ja=0,D=M[L].dependencies;ja<D.length;ja++)ia.push(aa(D[ja]));ja=0===ia.length?P(L):Promise.all(ia).then(function(){ea=Date.now()-Q;return P(L)});ja=ja.then(function(pa){if(C){var Z="Chunk ".concat(L," loaded in ").concat(Date.now()-Q," ms");-1!==ea&&(Z+=" (".concat(ea,
" ms for extra ").concat(ia.length," deps)"));C(0,306,50,Z)}return pa}).catch(function(pa){C&&C(0,306,10,pa)});Y.set(L,ja);return ja}}},"./lib/getOrderedScriptAndDependencies.js":function(u,E,G){Object.defineProperty(E,"__esModule",{value:!0});E.q_d=void 0;var I=G("../../.store/toposort@1.0.7-e70287510c5359da9183/node_modules/toposort/index.js");E.q_d=function(H,K){function C(){var L=M.shift();Y.add(L);var aa=K.get(L);aa&&aa.dependencies&&aa.dependencies.forEach(function(Q){Q=Q.toLowerCase();Y.has(Q)||
M.push(Q);P.push([Q,L])})}for(var Y=new Set,M=[H.toLowerCase()],P=[];0<M.length;)C();var T=[];Y.forEach(function(L){return T.push(L)});return I.BTb(T,P)}},"./lib/index.js":function(u,E,G){var I=this&&this.aCl||(Object.create?function(H,K,C,Y){void 0===Y&&(Y=C);var M=Object.getOwnPropertyDescriptor(K,C);if(!M||("get"in M?!K.A$:M.writable||M.configurable))M={enumerable:!0,get:function(){return K[C]}};Object.defineProperty(H,Y,M)}:function(H,K,C,Y){void 0===Y&&(Y=C);H[Y]=K[C]});u=this&&this.__exportStar||
function(H,K){for(var C in H)"default"===C||Object.prototype.hasOwnProperty.call(K,C)||I(K,H,C)};Object.defineProperty(E,"__esModule",{value:!0});u(G("./lib/DynamicScriptLoader.js"),E);u(G("./lib/loadScript.js"),E);u(G("./lib/preloadScript.js"),E);u(G("./lib/appResourceLoader.js"),E)},"./lib/loadScript.js":function(u,E){function G(I,H,K,C,Y,M,P){return new Promise(function(T,L){var aa=document.createElement("script");aa.async=!1;aa.src=H;void 0!==K&&(aa.crossOrigin=K);Y&&""!==Y&&(aa.setAttribute("integrity",
"sha256-".concat(Y)),K||(aa.crossOrigin="anonymous"));aa.onload=function(){M?M(I):T(I)};aa.onerror=function(){if(C&&0<C)document.head.removeChild(aa),G(I,H,K,C-1,Y,M||T,P||L);else{var Q=Error("Failed to download the script with identifier: ".concat(I," at url: ").concat(H));P?P(Q):L(Q)}};document.head.appendChild(aa)})}Object.defineProperty(E,"__esModule",{value:!0});E.loadScript=void 0;E.loadScript=function(I,H,K,C,Y,M){return G(I,H+(Y?"?cache-bust=true":""),K,C,M)}},"./lib/preloadScript.js":function(u,
E){Object.defineProperty(E,"__esModule",{value:!0});E.preloadScript=void 0;E.preloadScript=function(G,I){var H=document.createElement("link");H.rel="preload";H.href=G;H.setAttribute("as","script");void 0!==I&&(H.crossOrigin=I);document.head.appendChild(H)}}});Type.registerNamespace("Sys");window.IEnumerator=0;window.IEnumerable=1;(()=>{Type.registerNamespace("$$sc");window.$$ct=e;window.$$as=function(u,E){return u.isInstanceOfType(E)?E:null};m.Task.CKa=new A;v.a._default=new w;v.a.$x=v.a._default})();
Type.registerNamespace("Otel");window.otel=J;V;window.getDynamicScriptLoaderResolver=function(u,E,G,I,H,K,C,Y){return function(M,P){var T=H?"":".min",L=E,aa=I,Q=!1;K&&(Q=u.some(function(ea){return ea.identifier==M||null!=ea.dependencies&&-1<ea.dependencies.indexOf(M)}))&&(L=K+(P?"":"webpack/"),aa="localization/"+Y,T=C);return G&&!Q&&(Q=M.toLowerCase()+T+".js",G[Q])?G[Q]:L+(P?aa+"\\":"")+M+T+".js"}};window.newDynamicScriptLoader=function(u,E,G,I,H,K,C,Y,M){var P=getDynamicScriptLoaderResolver(E,G,
I,H,K,C,Y,M),T={resolveScript:function(L){return P(L.identifier,L.isLocalized)},crossOriginAttributeValue:u,knownScripts:E,loadScriptHandler:null};u=new y.DynamicScriptLoader(T);u.ZUe=function(L){T.loadScriptHandler=L};return u};window.getDynamicScriptLoaderFunction=function(u){return u.loadScript};window.dynamicScriptLoader=y;window.loadPreCore=()=>{d.e(1).then(d.bind(null,1195))}},function(J,V,d){d.d(V,"a",function(){return h});const h=e=>{e.next||(e.next=function(){return this.moveNext()?{done:!1,
value:this.get_current()}:{done:!0,value:void 0}},e[Symbol.iterator]=function(){return this});return e}},function(J,V,d){function h(e,m){return void 0==e||void 0==m?!1:"number"===typeof e||"string"===typeof e?Object.getType(m).implementsInterface(e):e.isInstanceOfType(m)}d.d(V,"a",function(){return h})}]),RO;for(RO in iF)nA[RO]=iF[RO];

//# sourceMappingURL=https://res-dev.cdn.officeppe.net/1js/build/17281904/wdjs/ppteditDS.precore.js.map